<?php

use Illuminate\Database\Seeder;

class DossiersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('dossiers')->delete();
        
        \DB::table('dossiers')->insert(array (
            0 => 
            array (
                'id' => '1',
                'patient_id' => '20',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '694580604',
                'portable_2' => '697945441',
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => NULL,
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => NULL,
                'date_naissance' => '2018-06-29',
                'created_at' => '2019-09-26 18:05:01',
                'updated_at' => '2019-09-26 18:05:01',
            ),
            1 => 
            array (
                'id' => '2',
                'patient_id' => '22',
                'sexe' => 'Masculin',
                'personne_confiance' => 'MANDENGUE Jean Roger',
                'tel_personne_confiance' => '699125835',
                'portable_1' => '699450465',
                'portable_2' => NULL,
                'personne_contact' => 'MANDENGUE Jean Roger',
                'tel_personne_contact' => '699125835',
                'profession' => 'Retraité',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'MOUTINBELEMBE',
                'date_naissance' => '1937-09-10',
                'created_at' => '2019-09-27 10:53:42',
                'updated_at' => '2019-09-27 10:53:42',
            ),
            2 => 
            array (
                'id' => '3',
                'patient_id' => '23',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699629282',
                'portable_2' => NULL,
                'personne_contact' => 'Mme BIMINA Céline',
                'tel_personne_contact' => '675712061',
                'profession' => 'Chauffeur',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'Deido/Dla',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1953-02-23',
                'created_at' => '2019-09-27 11:39:45',
                'updated_at' => '2019-09-27 11:39:45',
            ),
            3 => 
            array (
                'id' => '4',
                'patient_id' => '24',
                'sexe' => 'Masculin',
                'personne_confiance' => 'FELICITE',
                'tel_personne_confiance' => '694370639',
                'portable_1' => '652592537',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'IMPRIMEUR',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'NKONSAMBA',
                'date_naissance' => '1953-04-04',
                'created_at' => '2019-09-27 13:16:09',
                'updated_at' => '2019-09-27 13:16:09',
            ),
            4 => 
            array (
                'id' => '5',
                'patient_id' => '25',
                'sexe' => 'Féminin',
                'personne_confiance' => 'FILS TCHUENDEM',
                'tel_personne_confiance' => '674679453',
                'portable_1' => NULL,
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => NULL,
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'BAHAM',
                'date_naissance' => '1937-01-01',
                'created_at' => '2019-09-27 13:18:40',
                'updated_at' => '2019-09-27 13:18:40',
            ),
            5 => 
            array (
                'id' => '6',
                'patient_id' => '26',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '696364808',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'INFORMATICIEN',
                'email' => 'pauljean@yahoo.com',
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'SOUZA',
                'date_naissance' => '1959-07-20',
                'created_at' => '2019-09-27 13:21:27',
                'updated_at' => '2019-09-27 13:21:27',
            ),
            6 => 
            array (
                'id' => '7',
                'patient_id' => '27',
                'sexe' => 'Masculin',
                'personne_confiance' => 'Mère',
                'tel_personne_confiance' => '696099439',
                'portable_1' => NULL,
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => NULL,
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'Douala',
                'date_naissance' => '2016-01-01',
                'created_at' => '2019-09-27 13:23:19',
                'updated_at' => '2019-09-27 13:23:19',
            ),
            7 => 
            array (
                'id' => '8',
                'patient_id' => '28',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699572364',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'AVOCAT',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'NKONSAMBA',
                'date_naissance' => '1961-11-26',
                'created_at' => '2019-09-27 13:24:58',
                'updated_at' => '2019-09-27 13:24:58',
            ),
            8 => 
            array (
                'id' => '9',
                'patient_id' => '30',
                'sexe' => 'Masculin',
                'personne_confiance' => 'SOEUR TCHUENTEU',
                'tel_personne_confiance' => '699933532',
                'portable_1' => '699305040',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'COMMERÇANT',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'BAYANGAM',
                'date_naissance' => '1964-11-04',
                'created_at' => '2019-09-27 14:10:29',
                'updated_at' => '2019-09-27 14:10:29',
            ),
            9 => 
            array (
                'id' => '10',
                'patient_id' => '31',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '697778568',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'usinier',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'NKONSAMBA',
                'date_naissance' => '1970-10-01',
                'created_at' => '2019-09-27 14:18:29',
                'updated_at' => '2019-09-27 14:18:29',
            ),
            10 => 
            array (
                'id' => '11',
                'patient_id' => '32',
                'sexe' => 'Masculin',
                'personne_confiance' => 'FILS TCHUIBO',
                'tel_personne_confiance' => '699876249',
                'portable_1' => NULL,
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => NULL,
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'BAZOU',
                'date_naissance' => '1941-01-01',
                'created_at' => '2019-09-27 14:20:35',
                'updated_at' => '2019-09-27 14:20:35',
            ),
            11 => 
            array (
                'id' => '12',
                'patient_id' => '33',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '697106287',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => NULL,
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'BAZOU',
                'date_naissance' => '1948-01-01',
                'created_at' => '2019-09-27 14:21:44',
                'updated_at' => '2019-09-27 14:21:44',
            ),
            12 => 
            array (
                'id' => '13',
                'patient_id' => '34',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '651873435',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => NULL,
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'BARE',
                'date_naissance' => '1977-01-22',
                'created_at' => '2019-09-27 14:23:05',
                'updated_at' => '2019-09-27 14:23:05',
            ),
            13 => 
            array (
                'id' => '14',
                'patient_id' => '35',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '677763108',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'DIRECTEUR',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'KUMBA',
                'date_naissance' => '1967-03-18',
                'created_at' => '2019-09-27 14:24:18',
                'updated_at' => '2019-09-27 14:24:18',
            ),
            14 => 
            array (
                'id' => '15',
                'patient_id' => '36',
                'sexe' => 'Masculin',
                'personne_confiance' => 'FILLE TCHUISSEU',
                'tel_personne_confiance' => '679772785',
                'portable_1' => '677565674',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'CHAUFFEUR',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'BALENGOU',
                'date_naissance' => '1963-01-30',
                'created_at' => '2019-09-27 14:26:17',
                'updated_at' => '2019-09-27 14:26:17',
            ),
            15 => 
            array (
                'id' => '16',
                'patient_id' => '37',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699470891',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'DOCTEUR EN PHARMACIE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1977-02-20',
                'created_at' => '2019-09-27 14:28:22',
                'updated_at' => '2019-09-27 14:28:22',
            ),
            16 => 
            array (
                'id' => '17',
                'patient_id' => '38',
                'sexe' => 'Masculin',
                'personne_confiance' => 'MERE TCHUMAMO',
                'tel_personne_confiance' => '699095166',
                'portable_1' => NULL,
                'portable_2' => NULL,
                'personne_contact' => 'M TCHUMAMO',
                'tel_personne_contact' => '699412290',
                'profession' => 'ELEVE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'Douala',
                'date_naissance' => '2007-12-16',
                'created_at' => '2019-09-27 14:30:36',
                'updated_at' => '2019-09-27 14:30:36',
            ),
            17 => 
            array (
                'id' => '18',
                'patient_id' => '39',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '696180744',
                'portable_2' => '670022093',
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'TECHNICIEN EN BÂTIMENT',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => NULL,
                'date_naissance' => '1990-03-07',
                'created_at' => '2019-09-27 14:32:52',
                'updated_at' => '2019-09-27 14:32:52',
            ),
            18 => 
            array (
                'id' => '19',
                'patient_id' => '40',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699628172',
                'portable_2' => '651696591',
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'LOGISTICIEN',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'DSCHANG',
                'date_naissance' => '1980-08-04',
                'created_at' => '2019-09-27 14:34:37',
                'updated_at' => '2019-09-27 14:34:37',
            ),
            19 => 
            array (
                'id' => '20',
                'patient_id' => '41',
                'sexe' => 'Féminin',
                'personne_confiance' => 'FRERE',
                'tel_personne_confiance' => '694995924',
                'portable_1' => NULL,
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'FISCALISTE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'BANKA',
                'date_naissance' => '1985-02-27',
                'created_at' => '2019-09-27 14:35:59',
                'updated_at' => '2019-09-27 14:35:59',
            ),
            20 => 
            array (
                'id' => '21',
                'patient_id' => '42',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '675279753',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'CADRE ADMINISTRATIF',
                'email' => NULL,
                'fax' => 'BP 722 DOUALA',
                'adresse' => NULL,
                'lieu_naissance' => 'MOKOLO',
                'date_naissance' => '1985-03-14',
                'created_at' => '2019-09-27 14:42:37',
                'updated_at' => '2019-09-27 14:42:37',
            ),
            21 => 
            array (
                'id' => '22',
                'patient_id' => '43',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '677761916',
                'portable_2' => '694542325',
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'ELECTRICIEN',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'BAKOU',
                'date_naissance' => '1951-01-01',
                'created_at' => '2019-09-27 14:44:15',
                'updated_at' => '2019-09-27 14:44:15',
            ),
            22 => 
            array (
                'id' => '23',
                'patient_id' => '44',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699890821',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'CHEF D\'ENTREPRISE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1963-09-10',
                'created_at' => '2019-09-27 14:45:44',
                'updated_at' => '2019-09-27 14:45:44',
            ),
            23 => 
            array (
                'id' => '24',
                'patient_id' => '45',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '675115820',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'TECHNICIEN-MEDICO',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'FONDENERA',
                'date_naissance' => '1983-10-08',
                'created_at' => '2019-09-27 14:47:04',
                'updated_at' => '2019-09-27 14:47:04',
            ),
            24 => 
            array (
                'id' => '25',
                'patient_id' => '29',
                'sexe' => 'Masculin',
                'personne_confiance' => 'Mr akoum eric',
                'tel_personne_confiance' => '677264128',
                'portable_1' => '675932902',
                'portable_2' => '667649564',
                'personne_contact' => 'awantag henri',
                'tel_personne_contact' => '675426280',
                'profession' => 'mecanicien',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'bonaberie',
                'lieu_naissance' => 'bamenda',
                'date_naissance' => '1986-01-07',
                'created_at' => '2019-09-27 15:27:25',
                'updated_at' => '2019-09-27 15:27:25',
            ),
            25 => 
            array (
                'id' => '26',
                'patient_id' => '47',
                'sexe' => 'Masculin',
            'personne_confiance' => 'mr tchinda ernest magloire( pere)',
                'tel_personne_confiance' => '699470792',
                'portable_1' => NULL,
                'portable_2' => NULL,
            'personne_contact' => 'mme mindji onacis nadège( mere)',
                'tel_personne_contact' => '699893863',
                'profession' => 'eleve',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => NULL,
                'date_naissance' => '2009-03-02',
                'created_at' => '2019-09-27 16:28:35',
                'updated_at' => '2019-09-27 16:28:35',
            ),
            26 => 
            array (
                'id' => '27',
                'patient_id' => '57',
                'sexe' => 'Masculin',
            'personne_confiance' => 'mr ngafarou( sons fils)',
                'tel_personne_confiance' => '660918197',
                'portable_1' => '663721879',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'cultivateur',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'fouban',
                'lieu_naissance' => 'fouban',
                'date_naissance' => '1956-02-13',
                'created_at' => '2019-10-01 10:30:14',
                'updated_at' => '2019-10-01 10:30:14',
            ),
            27 => 
            array (
                'id' => '28',
                'patient_id' => '57',
                'sexe' => 'Masculin',
            'personne_confiance' => 'mr ngafarou( sons fils)',
                'tel_personne_confiance' => '660918197',
                'portable_1' => '663721879',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'cultivateur',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'fouban',
                'lieu_naissance' => 'fouban',
                'date_naissance' => '1956-02-13',
                'created_at' => '2019-10-01 10:34:44',
                'updated_at' => '2019-10-01 10:34:44',
            ),
            28 => 
            array (
                'id' => '29',
                'patient_id' => '60',
                'sexe' => 'Masculin',
                'personne_confiance' => 'mme kengne liliane',
                'tel_personne_confiance' => '694268890',
                'portable_1' => '675791261',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'retraité',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'tamdja baffoussam',
                'lieu_naissance' => 'bafoussam',
                'date_naissance' => '1939-01-01',
                'created_at' => '2019-10-01 11:17:08',
                'updated_at' => '2019-10-01 11:17:08',
            ),
            29 => 
            array (
                'id' => '30',
                'patient_id' => '61',
                'sexe' => 'Masculin',
            'personne_confiance' => 'mme irene ndome( sa fille)',
                'tel_personne_confiance' => '699651939',
                'portable_1' => NULL,
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'ingenieur',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'dauala bonaminkengue',
                'lieu_naissance' => 'douala',
                'date_naissance' => '1954-01-29',
                'created_at' => '2019-10-01 11:29:34',
                'updated_at' => '2019-10-01 11:29:34',
            ),
            30 => 
            array (
                'id' => '31',
                'patient_id' => '59',
                'sexe' => 'Masculin',
                'personne_confiance' => 'mme fopa',
                'tel_personne_confiance' => '677924147',
                'portable_1' => '695443736',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'chef d\'entreprise',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'douala bassa pk 12',
                'lieu_naissance' => NULL,
                'date_naissance' => '1960-01-01',
                'created_at' => '2019-10-01 11:35:31',
                'updated_at' => '2019-10-01 11:35:31',
            ),
            31 => 
            array (
                'id' => '32',
                'patient_id' => '62',
                'sexe' => 'Masculin',
                'personne_confiance' => 'mme tiekam',
                'tel_personne_confiance' => '696248812',
                'portable_1' => '674122967',
                'portable_2' => '697145376',
                'personne_contact' => 'mme debizan regine',
                'tel_personne_contact' => '699843839',
                'profession' => 'juriste',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'lendi',
                'lieu_naissance' => NULL,
                'date_naissance' => '1984-10-26',
                'created_at' => '2019-10-01 12:00:27',
                'updated_at' => '2019-10-01 12:00:27',
            ),
            32 => 
            array (
                'id' => '33',
                'patient_id' => '64',
                'sexe' => 'Masculin',
                'personne_confiance' => 'Mme BOGMIS CLAIRE',
                'tel_personne_confiance' => '699756636',
                'portable_1' => '694231218',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'FONCTIONNAIRE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'Emobo 2/yaounde',
                'lieu_naissance' => 'EKOEANEN/nyon-ekele',
                'date_naissance' => '1978-01-24',
                'created_at' => '2019-10-01 14:49:34',
                'updated_at' => '2019-10-01 14:49:34',
            ),
            33 => 
            array (
                'id' => '34',
                'patient_id' => '70',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699956565',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'COMMERÇANT',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'MLI NIOROKAYES',
                'date_naissance' => '1974-04-30',
                'created_at' => '2019-10-02 15:23:46',
                'updated_at' => '2019-10-02 15:23:46',
            ),
            34 => 
            array (
                'id' => '35',
                'patient_id' => '70',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699956565',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'COMMERÇANT',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'MLI NIOROKAYES',
                'date_naissance' => '1974-04-30',
                'created_at' => '2019-10-02 15:30:54',
                'updated_at' => '2019-10-02 15:30:54',
            ),
            35 => 
            array (
                'id' => '36',
                'patient_id' => '75',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699624622',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => NULL,
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'bann',
                'date_naissance' => '1948-02-01',
                'created_at' => '2019-10-03 11:16:50',
                'updated_at' => '2019-10-03 11:16:50',
            ),
            36 => 
            array (
                'id' => '37',
                'patient_id' => '75',
                'sexe' => 'Masculin',
                'personne_confiance' => 'fille',
                'tel_personne_confiance' => '693306038',
                'portable_1' => '699624622',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'déclarant en douane',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'bann',
                'date_naissance' => '1948-02-01',
                'created_at' => '2019-10-03 11:19:15',
                'updated_at' => '2019-10-03 11:19:15',
            ),
            37 => 
            array (
                'id' => '38',
                'patient_id' => '76',
                'sexe' => 'Féminin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '670296749',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'Enseignante',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'YINGUI',
                'lieu_naissance' => NULL,
                'date_naissance' => '1988-06-26',
                'created_at' => '2019-10-03 11:39:50',
                'updated_at' => '2019-10-03 11:39:50',
            ),
            38 => 
            array (
                'id' => '39',
                'patient_id' => '75',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699624622',
                'portable_2' => '675276322',
                'personne_contact' => 'Fille',
                'tel_personne_contact' => '693306038',
                'profession' => 'Déclarant en douane',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'PK11 Douala',
                'lieu_naissance' => 'Bann',
                'date_naissance' => '1948-02-01',
                'created_at' => '2019-10-03 11:50:34',
                'updated_at' => '2019-10-03 11:50:34',
            ),
            39 => 
            array (
                'id' => '40',
                'patient_id' => '78',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '673752285',
                'portable_2' => NULL,
                'personne_contact' => 'mere',
                'tel_personne_contact' => '674753698',
                'profession' => 'ingenieur',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'yaounde',
                'date_naissance' => '1990-03-31',
                'created_at' => '2019-10-04 09:46:46',
                'updated_at' => '2019-10-04 09:46:46',
            ),
            40 => 
            array (
                'id' => '41',
                'patient_id' => '79',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '678674726',
                'portable_2' => NULL,
                'personne_contact' => 'epouse',
                'tel_personne_contact' => '679753245',
                'profession' => 'teacher',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'tiko',
                'lieu_naissance' => 'balinyonga',
                'date_naissance' => '1973-11-02',
                'created_at' => '2019-10-04 10:06:11',
                'updated_at' => '2019-10-04 10:06:11',
            ),
            41 => 
            array (
                'id' => '42',
                'patient_id' => '82',
                'sexe' => 'Masculin',
                'personne_confiance' => 'soeur',
                'tel_personne_confiance' => '690988147',
                'portable_1' => '693121770',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'predicateur',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'douala',
                'date_naissance' => '1963-08-23',
                'created_at' => '2019-10-04 14:27:00',
                'updated_at' => '2019-10-04 14:27:00',
            ),
            42 => 
            array (
                'id' => '43',
                'patient_id' => '106',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '679525674',
                'portable_2' => NULL,
                'personne_contact' => 'NELSON',
                'tel_personne_contact' => '696398356',
                'profession' => 'Logisticien',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'Nkomondo',
                'lieu_naissance' => NULL,
                'date_naissance' => '1973-06-25',
                'created_at' => '2019-10-12 14:56:20',
                'updated_at' => '2019-10-12 14:56:20',
            ),
            43 => 
            array (
                'id' => '44',
                'patient_id' => '133',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '677308179',
                'portable_2' => NULL,
                'personne_contact' => 'Mr. NDOCKY Frank Peter',
                'tel_personne_contact' => '678663704',
                'profession' => 'farmer',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1971-09-25',
                'created_at' => '2019-10-18 13:04:12',
                'updated_at' => '2019-10-18 13:04:12',
            ),
            44 => 
            array (
                'id' => '45',
                'patient_id' => '139',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699850902',
                'portable_2' => NULL,
                'personne_contact' => 'mr edia',
                'tel_personne_contact' => '697119864',
                'profession' => 'retraite',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'new bell',
                'lieu_naissance' => 'Bafang',
                'date_naissance' => '1945-10-11',
                'created_at' => '2019-10-22 09:55:14',
                'updated_at' => '2019-10-22 09:55:14',
            ),
            45 => 
            array (
                'id' => '47',
                'patient_id' => '146',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '671351932',
                'portable_2' => NULL,
                'personne_contact' => 'grand frere',
                'tel_personne_contact' => '673077145',
                'profession' => 'eleve',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'sohock',
                'date_naissance' => '1987-04-15',
                'created_at' => '2019-10-23 12:11:15',
                'updated_at' => '2019-10-23 12:11:15',
            ),
            46 => 
            array (
                'id' => '48',
                'patient_id' => '147',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '675701695',
                'portable_2' => NULL,
                'personne_contact' => 'frere',
                'tel_personne_contact' => '617448809',
                'profession' => 'mecanien',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'bamendjo',
                'date_naissance' => '1995-09-10',
                'created_at' => '2019-10-23 12:33:37',
                'updated_at' => '2019-10-23 12:33:37',
            ),
            47 => 
            array (
                'id' => '49',
                'patient_id' => '150',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => NULL,
                'portable_2' => NULL,
                'personne_contact' => 'Mme MAYI Monique',
                'tel_personne_contact' => NULL,
                'profession' => 'Elève',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'Douala',
                'date_naissance' => '2002-06-07',
                'created_at' => '2019-10-24 10:05:11',
                'updated_at' => '2019-10-24 10:05:11',
            ),
            48 => 
            array (
                'id' => '50',
                'patient_id' => '151',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '675412947',
                'portable_2' => NULL,
                'personne_contact' => 'mme. MOFO Christine',
                'tel_personne_contact' => '677421042',
                'profession' => 'homme d\'affaire',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'Bamenyam',
                'date_naissance' => '1958-02-11',
                'created_at' => '2019-10-24 11:03:29',
                'updated_at' => '2019-10-24 11:03:29',
            ),
            49 => 
            array (
                'id' => '51',
                'patient_id' => '152',
                'sexe' => 'Féminin',
                'personne_confiance' => 'MR. ABDELKARIM',
                'tel_personne_confiance' => '675303077',
                'portable_1' => NULL,
                'portable_2' => NULL,
                'personne_contact' => 'MR. ABDELKARIM',
                'tel_personne_contact' => '696081533',
                'profession' => 'MENAGERE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'MAKONG',
                'date_naissance' => '1977-01-01',
                'created_at' => '2019-10-24 11:22:45',
                'updated_at' => '2019-10-24 11:22:45',
            ),
            50 => 
            array (
                'id' => '52',
                'patient_id' => '150',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => NULL,
                'portable_2' => NULL,
                'personne_contact' => 'Mme MAYI Monique',
                'tel_personne_contact' => '696099439',
                'profession' => NULL,
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'Douala',
                'date_naissance' => '2002-06-07',
                'created_at' => '2019-10-26 18:58:43',
                'updated_at' => '2019-10-26 18:58:43',
            ),
            51 => 
            array (
                'id' => '53',
                'patient_id' => '168',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699195889',
                'portable_2' => NULL,
                'personne_contact' => 'epouse',
                'tel_personne_contact' => '656672554',
                'profession' => 'ingenieur en telecom,',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'yaounde',
                'date_naissance' => '1987-03-08',
                'created_at' => '2019-10-29 16:04:40',
                'updated_at' => '2019-10-29 16:04:40',
            ),
            52 => 
            array (
                'id' => '54',
                'patient_id' => '171',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '675859871',
                'portable_2' => '699500264',
                'personne_contact' => 'epouse',
                'tel_personne_contact' => '695048787',
                'profession' => 'COMMERÇANT',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'mbo bandjoun',
                'date_naissance' => '1982-03-20',
                'created_at' => '2019-10-31 09:00:41',
                'updated_at' => '2019-10-31 09:00:41',
            ),
            53 => 
            array (
                'id' => '55',
                'patient_id' => '196',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699526294',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'Entrepreneur',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'France',
                'lieu_naissance' => 'France',
                'date_naissance' => '1970-08-23',
                'created_at' => '2019-11-06 17:23:15',
                'updated_at' => '2019-11-06 17:23:15',
            ),
            54 => 
            array (
                'id' => '56',
                'patient_id' => '104',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '698482572',
                'portable_2' => '675772901',
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'Ingenieur Electromecanicien',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'Yde-Stinga',
                'lieu_naissance' => 'Batsela Poumougne',
                'date_naissance' => '1961-10-01',
                'created_at' => '2019-11-06 17:28:01',
                'updated_at' => '2019-11-06 17:28:01',
            ),
            55 => 
            array (
                'id' => '57',
                'patient_id' => '198',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699918182',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'Directeur de Ste',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'Kekem',
                'lieu_naissance' => 'KEKEM',
                'date_naissance' => '1953-01-01',
                'created_at' => '2019-11-06 17:30:14',
                'updated_at' => '2019-11-06 17:30:14',
            ),
            56 => 
            array (
                'id' => '58',
                'patient_id' => '199',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '677788503',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'RETRAITE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'MAKEPE',
                'lieu_naissance' => 'BAGANTE',
                'date_naissance' => '1941-12-12',
                'created_at' => '2019-11-06 17:35:00',
                'updated_at' => '2019-11-06 17:35:00',
            ),
            57 => 
            array (
                'id' => '59',
                'patient_id' => '200',
                'sexe' => 'Féminin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '677547406',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'Infirmiere',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'Buea',
                'lieu_naissance' => 'loum',
                'date_naissance' => '1964-07-26',
                'created_at' => '2019-11-06 17:59:55',
                'updated_at' => '2019-11-06 17:59:55',
            ),
            58 => 
            array (
                'id' => '60',
                'patient_id' => '187',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => NULL,
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'enseignant',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'douala',
                'lieu_naissance' => 'buea',
                'date_naissance' => '1958-03-07',
                'created_at' => '2019-11-06 19:00:11',
                'updated_at' => '2019-11-06 19:00:11',
            ),
            59 => 
            array (
                'id' => '61',
                'patient_id' => '190',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699886890',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'ENSEIGNANT D\'UNIVERSITE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'YAOUNDE-MIMBOMAN I',
                'lieu_naissance' => 'NKOLEBOUMA',
                'date_naissance' => '1945-05-05',
                'created_at' => '2019-11-06 19:22:10',
                'updated_at' => '2019-11-06 19:22:10',
            ),
            60 => 
            array (
                'id' => '62',
                'patient_id' => '202',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '653537090',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'Huissier',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => '1747-BEAC DOUALA',
                'lieu_naissance' => 'Yaounde',
                'date_naissance' => '1960-01-11',
                'created_at' => '2019-11-06 19:44:13',
                'updated_at' => '2019-11-06 19:44:13',
            ),
            61 => 
            array (
                'id' => '63',
                'patient_id' => '194',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '698003252',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'Commerçant',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'douala',
                'lieu_naissance' => 'BANGOU',
                'date_naissance' => '1956-11-06',
                'created_at' => '2019-11-06 20:17:53',
                'updated_at' => '2019-11-06 20:17:53',
            ),
            62 => 
            array (
                'id' => '64',
                'patient_id' => '195',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '679649409',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'Ingenieur',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'Douala',
                'lieu_naissance' => 'BAHAM',
                'date_naissance' => '1968-02-01',
                'created_at' => '2019-11-06 20:43:04',
                'updated_at' => '2019-11-06 20:43:04',
            ),
            63 => 
            array (
                'id' => '65',
                'patient_id' => '204',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699360547',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'RETRAITE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'BAHAM',
                'lieu_naissance' => 'BAHAM',
                'date_naissance' => '1942-01-01',
                'created_at' => '2019-11-07 13:03:53',
                'updated_at' => '2019-11-07 13:03:53',
            ),
            64 => 
            array (
                'id' => '66',
                'patient_id' => '205',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '658023538',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'Ingenieur des eaux et foret',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'DJOUM',
                'lieu_naissance' => 'DOUALA',
                'date_naissance' => '1985-09-22',
                'created_at' => '2019-11-07 13:05:45',
                'updated_at' => '2019-11-07 13:05:45',
            ),
            65 => 
            array (
                'id' => '67',
                'patient_id' => '207',
                'sexe' => 'Masculin',
                'personne_confiance' => 'Mr NONG PASCAL',
                'tel_personne_confiance' => '676400876',
                'portable_1' => '658936173',
                'portable_2' => NULL,
                'personne_contact' => 'Mme NONG BERTHE BERENISE',
                'tel_personne_contact' => '676032427',
                'profession' => 'RETRAITE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'COMODO DOUALA',
                'lieu_naissance' => 'DOUALA',
                'date_naissance' => '1955-01-01',
                'created_at' => '2019-11-07 13:54:19',
                'updated_at' => '2019-11-07 13:54:19',
            ),
            66 => 
            array (
                'id' => '68',
                'patient_id' => '208',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '677115206',
                'portable_2' => NULL,
                'personne_contact' => 'MME TAGNE',
                'tel_personne_contact' => '673458845',
                'profession' => 'RETRAITE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'ANGE RAPHAEL',
                'lieu_naissance' => 'BAWAN',
                'date_naissance' => '1944-01-01',
                'created_at' => '2019-11-07 14:50:33',
                'updated_at' => '2019-11-07 14:50:33',
            ),
            67 => 
            array (
                'id' => '69',
                'patient_id' => '112',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699927087',
                'portable_2' => NULL,
                'personne_contact' => 'épouse',
                'tel_personne_contact' => '699968698',
                'profession' => 'Officier d\'armée',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'Bonamoussadi',
                'lieu_naissance' => 'Batie',
                'date_naissance' => '1952-01-01',
                'created_at' => '2019-11-07 18:12:29',
                'updated_at' => '2019-11-07 18:12:29',
            ),
            68 => 
            array (
                'id' => '70',
                'patient_id' => '221',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '655339742',
                'portable_2' => NULL,
                'personne_contact' => 'mme obono zeng',
                'tel_personne_contact' => '679920058',
                'profession' => NULL,
                'email' => 'stephane_zeng@yahoo.fr',
                'fax' => NULL,
                'adresse' => 'yaounde',
                'lieu_naissance' => 'EBOLOWA',
                'date_naissance' => '1996-06-13',
                'created_at' => '2019-11-11 10:23:27',
                'updated_at' => '2019-11-11 10:23:27',
            ),
            69 => 
            array (
                'id' => '71',
                'patient_id' => '222',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '695694986',
                'portable_2' => NULL,
                'personne_contact' => 'mme ngatchou',
                'tel_personne_contact' => '677148270',
                'profession' => 'déclarent en douane',
                'email' => 'blaise.ngatchou@yahoo.fr',
                'fax' => NULL,
                'adresse' => 'logbessou',
                'lieu_naissance' => 'DOUALA',
                'date_naissance' => '1969-12-16',
                'created_at' => '2019-11-11 10:34:43',
                'updated_at' => '2019-11-11 10:34:43',
            ),
            70 => 
            array (
                'id' => '72',
                'patient_id' => '228',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '656356411',
                'portable_2' => NULL,
                'personne_contact' => 'MR FANKAM',
                'tel_personne_contact' => '699746917',
                'profession' => NULL,
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'DOUALA',
                'date_naissance' => '2002-06-05',
                'created_at' => '2019-11-12 08:33:34',
                'updated_at' => '2019-11-12 08:33:34',
            ),
            71 => 
            array (
                'id' => '73',
                'patient_id' => '231',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '675858683',
                'portable_2' => NULL,
                'personne_contact' => 'MME FEUTSEU',
                'tel_personne_contact' => '652916331',
                'profession' => 'CHAUFFEUR',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'NEW-BELL',
                'lieu_naissance' => 'BARE',
                'date_naissance' => '1968-11-07',
                'created_at' => '2019-11-12 09:54:45',
                'updated_at' => '2019-11-12 09:54:45',
            ),
            72 => 
            array (
                'id' => '74',
                'patient_id' => '232',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699892679',
                'portable_2' => NULL,
                'personne_contact' => 'MME BASOH',
                'tel_personne_contact' => '699695966',
                'profession' => NULL,
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'Douala',
                'lieu_naissance' => 'MBO',
                'date_naissance' => '1975-12-25',
                'created_at' => '2019-11-12 10:06:52',
                'updated_at' => '2019-11-12 10:06:52',
            ),
            73 => 
            array (
                'id' => '75',
                'patient_id' => '238',
                'sexe' => 'Féminin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699891174',
                'portable_2' => NULL,
                'personne_contact' => 'MME MNONDJO',
                'tel_personne_contact' => '699906373',
                'profession' => NULL,
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'PK10 COLONEL',
                'lieu_naissance' => 'DOUALA',
                'date_naissance' => '1945-09-06',
                'created_at' => '2019-11-13 09:27:49',
                'updated_at' => '2019-11-13 09:27:49',
            ),
            74 => 
            array (
                'id' => '76',
                'patient_id' => '247',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '674888888',
                'portable_2' => NULL,
                'personne_contact' => 'son fils',
                'tel_personne_contact' => '651919857',
                'profession' => 'Business man',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => NULL,
                'date_naissance' => '1954-11-30',
                'created_at' => '2019-11-14 11:49:24',
                'updated_at' => '2019-11-14 11:49:24',
            ),
            75 => 
            array (
                'id' => '77',
                'patient_id' => '253',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '694040291',
                'portable_2' => NULL,
                'personne_contact' => 'MME MBA',
                'tel_personne_contact' => '693177032',
                'profession' => 'CONCEPTEUR',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'VICTOIREMBA91@YAHOO.FR',
                'lieu_naissance' => 'BANSOA',
                'date_naissance' => '1986-03-13',
                'created_at' => '2019-11-18 08:13:21',
                'updated_at' => '2019-11-18 08:13:21',
            ),
            76 => 
            array (
                'id' => '78',
                'patient_id' => '255',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '697158608',
                'portable_2' => NULL,
                'personne_contact' => 'PAPA',
                'tel_personne_contact' => '699998384',
                'profession' => 'VENDEUR',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'BAGANGTE',
                'lieu_naissance' => 'FANDA',
                'date_naissance' => '1976-05-09',
                'created_at' => '2019-11-18 08:53:15',
                'updated_at' => '2019-11-18 08:53:15',
            ),
            77 => 
            array (
                'id' => '79',
                'patient_id' => '225',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699795346',
                'portable_2' => NULL,
                'personne_contact' => 'son epouse',
                'tel_personne_contact' => '699077896',
                'profession' => 'expert judiciaire',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1963-11-01',
                'created_at' => '2019-11-18 11:55:02',
                'updated_at' => '2019-11-18 11:55:02',
            ),
            78 => 
            array (
                'id' => '80',
                'patient_id' => '258',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '699438913',
                'portable_2' => NULL,
                'personne_contact' => 'MR NGWEND  NTAMACK',
                'tel_personne_contact' => '699438913',
                'profession' => 'RETRAITE',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'NDOGBIYICK',
                'date_naissance' => '1939-11-25',
                'created_at' => '2019-11-18 15:43:12',
                'updated_at' => '2019-11-18 15:43:12',
            ),
            79 => 
            array (
                'id' => '81',
                'patient_id' => '225',
                'sexe' => 'Masculin',
                'personne_confiance' => 'Epouse',
                'tel_personne_confiance' => '699077896',
                'portable_1' => '699795346',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'expert judiciaire',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'Douala',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1963-11-01',
                'created_at' => '2019-11-18 18:08:43',
                'updated_at' => '2019-11-18 18:08:43',
            ),
            80 => 
            array (
                'id' => '82',
                'patient_id' => '249',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => NULL,
                'portable_2' => NULL,
                'personne_contact' => 'sa fille',
                'tel_personne_contact' => '696586562',
                'profession' => 'retraité',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'bandjoun',
                'date_naissance' => '1932-01-01',
                'created_at' => '2019-11-22 10:15:52',
                'updated_at' => '2019-11-22 10:15:52',
            ),
            81 => 
            array (
                'id' => '83',
                'patient_id' => '158',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '677701255',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'retraité',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => NULL,
                'lieu_naissance' => 'FONDJO MEKWET',
                'date_naissance' => '1936-01-01',
                'created_at' => '2019-11-25 19:33:34',
                'updated_at' => '2019-11-25 19:33:34',
            ),
            82 => 
            array (
                'id' => '84',
                'patient_id' => '158',
                'sexe' => 'Masculin',
                'personne_confiance' => 'FILLE',
                'tel_personne_confiance' => '699969594',
                'portable_1' => '677701255',
                'portable_2' => NULL,
                'personne_contact' => NULL,
                'tel_personne_contact' => NULL,
                'profession' => 'Retraité',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'MAKEPE',
                'lieu_naissance' => 'FONDJO MEKWET',
                'date_naissance' => '1936-01-01',
                'created_at' => '2019-11-25 19:38:53',
                'updated_at' => '2019-11-25 19:38:53',
            ),
            83 => 
            array (
                'id' => '85',
                'patient_id' => '283',
                'sexe' => 'Masculin',
                'personne_confiance' => NULL,
                'tel_personne_confiance' => NULL,
                'portable_1' => '690456566',
                'portable_2' => NULL,
                'personne_contact' => 'epouse',
                'tel_personne_contact' => '690456566',
                'profession' => 'employe de banque',
                'email' => NULL,
                'fax' => NULL,
                'adresse' => 'Douala',
                'lieu_naissance' => 'DOUALA',
                'date_naissance' => '1959-11-19',
                'created_at' => '2019-11-27 12:19:00',
                'updated_at' => '2019-11-27 12:19:00',
            ),
        ));
        
        
    }
}