<?php

use Illuminate\Database\Seeder;

class SurveillanceRapprocheParametresTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('surveillance_rapproche_parametres')->delete();
        
        \DB::table('surveillance_rapproche_parametres')->insert(array (
            0 => 
            array (
                'id' => '1',
                'user_id' => '8',
                'patient_id' => '21',
                'date' => '2019-10-30',
                'heure' => '06:30',
                'ta' => '149/95',
                'fr' => '18',
                'pouls' => '85',
                'spo2' => '99',
                'temperature' => '37.1',
                'diurese' => 'N/A',
                'conscience' => 'OUI',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'pas de plaintes
nuit calme',
                'periode' => 'postoperatoire',
            ),
            1 => 
            array (
                'id' => '2',
                'user_id' => '12',
                'patient_id' => '198',
                'date' => '2019-11-07',
                'heure' => '08:12',
                'ta' => '157/83',
                'fr' => '20',
                'pouls' => '82',
                'spo2' => '98',
                'temperature' => '37.2',
                'diurese' => 'ND',
                'conscience' => 'So',
                'douleur' => '2',
                'observation_plainte' => 'RAS',
                'periode' => 'preoperatoire',
            ),
            2 => 
            array (
                'id' => '3',
                'user_id' => '12',
                'patient_id' => '198',
                'date' => '2019-11-07',
                'heure' => '12:20',
                'ta' => '156/88',
                'fr' => '18',
                'pouls' => '86',
                'spo2' => '99',
                'temperature' => '36',
                'diurese' => 'SV:200cc',
                'conscience' => 'S1',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'sortir du patient du bloc opératoire 1',
                'periode' => 'postoperatoire',
            ),
            3 => 
            array (
                'id' => '4',
                'user_id' => '12',
                'patient_id' => '198',
                'date' => '2019-11-07',
                'heure' => '13:00',
                'ta' => '133/74',
                'fr' => '18',
                'pouls' => '82',
                'spo2' => '99',
                'temperature' => '36.5',
                'diurese' => 'SV:200cc',
                'conscience' => 'So',
                'douleur' => 'EVA;0',
                'observation_plainte' => 'RAS',
                'periode' => 'postoperatoire',
            ),
            4 => 
            array (
                'id' => '5',
                'user_id' => '12',
                'patient_id' => '198',
                'date' => '2019-11-07',
                'heure' => '13:30',
                'ta' => '138/75',
                'fr' => '18',
                'pouls' => '86',
                'spo2' => '99',
                'temperature' => '36.6',
                'diurese' => 'SV:200cc',
                'conscience' => 'so',
                'douleur' => 'EVA',
                'observation_plainte' => 'urine claire ,glycémie post op immédiat 1.61gl ,hydratation ok,pas de plainte',
                'periode' => 'postoperatoire',
            ),
            5 => 
            array (
                'id' => '6',
                'user_id' => '12',
                'patient_id' => '198',
                'date' => '2019-11-07',
                'heure' => '14:30',
                'ta' => '136/72',
                'fr' => '18',
                'pouls' => '80',
                'spo2' => '99',
                'temperature' => '36.7',
                'diurese' => 'SV:200CC',
                'conscience' => 'SO',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'RAS',
                'periode' => 'postoperatoire',
            ),
            6 => 
            array (
                'id' => '7',
                'user_id' => '4',
                'patient_id' => '198',
                'date' => '2019-11-07',
                'heure' => '17:00',
                'ta' => '138/77',
                'fr' => '18',
                'pouls' => '82',
                'spo2' => '99',
                'temperature' => '36.5',
                'diurese' => '300',
                'conscience' => 'so',
                'douleur' => '1',
                'observation_plainte' => 'patient stable ,a pris un pot de yaourt+ salade de fruit',
                'periode' => 'postoperatoire',
            ),
            7 => 
            array (
                'id' => '8',
                'user_id' => '4',
                'patient_id' => '112',
                'date' => '2019-11-07',
                'heure' => '09:30',
                'ta' => '169/98',
                'fr' => '18',
                'pouls' => '67',
                'spo2' => '99',
                'temperature' => '36.9',
                'diurese' => NULL,
                'conscience' => 'so',
                'douleur' => '0',
                'observation_plainte' => 'dernier pris à21h ,glyc pris a jeun:1.18g/l',
                'periode' => 'preoperatoire',
            ),
            8 => 
            array (
                'id' => '9',
                'user_id' => '4',
                'patient_id' => '112',
                'date' => '2019-11-07',
                'heure' => '18:00',
                'ta' => '183/88',
                'fr' => '18',
                'pouls' => '50',
                'spo2' => '100',
                'temperature' => '36.6',
                'diurese' => 'dl:100cc/sv:400cc',
                'conscience' => 'so',
                'douleur' => '4',
                'observation_plainte' => 'eva:4 cat:nefopam20mg:3amp dans 250cc passé en 30 mn po dr sandjon.',
                'periode' => 'postoperatoire',
            ),
            9 => 
            array (
                'id' => '10',
                'user_id' => '6',
                'patient_id' => '112',
                'date' => '2019-11-07',
                'heure' => '20:05',
                'ta' => '160/86mmhg',
                'fr' => '18',
                'pouls' => '94',
                'spo2' => '100',
                'temperature' => '36.5',
            'diurese' => '1500ml d\'urine hematique. ( poche vidée)',
                'conscience' => 'oui',
                'douleur' => 'EVA=3',
                'observation_plainte' => '- drain: 200ml d\'urine hematique, 
- arrêt oxygene, 
- plaintes: douleurs au site opératoire surtout à l\'hypogastre.',
                'periode' => 'postoperatoire',
            ),
            10 => 
            array (
                'id' => '11',
                'user_id' => '6',
                'patient_id' => '112',
                'date' => '2019-11-08',
                'heure' => '05:30',
                'ta' => '158/91',
                'fr' => '18',
                'pouls' => '82',
                'spo2' => '99',
                'temperature' => '37',
            'diurese' => '800 ml d\'urines rosées ( poche vidée)',
                'conscience' => 'oui',
                'douleur' => 'EVA=1',
                'observation_plainte' => '- Bain pris, 
- Pansement refait,
- pas de plaintes exprimées ce matin,
- glycémie à jeune: 2.44 g/l Janumet 50mg/1000mg pris',
                'periode' => 'postoperatoire',
            ),
            11 => 
            array (
                'id' => '12',
                'user_id' => '6',
                'patient_id' => '198',
                'date' => '2019-11-08',
                'heure' => '06:00',
                'ta' => '162/78mmhg',
                'fr' => '18',
                'pouls' => '88',
                'spo2' => '99',
                'temperature' => '37',
            'diurese' => '1200ml d\'urines rosées ( poche vidée)',
                'conscience' => 'oui',
                'douleur' => 'EVA=0',
                'observation_plainte' => '- Bain pris ce matin
- Pas de plaintes exprimées 
- Glycémie: 1.36g/l    Glucophage 1000mg pris,
- FLUDEX 1.5 g pris',
                'periode' => 'postoperatoire',
            ),
            12 => 
            array (
                'id' => '13',
                'user_id' => '12',
                'patient_id' => '204',
                'date' => '2019-11-08',
                'heure' => '08:00',
                'ta' => '118/68',
                'fr' => '17',
                'pouls' => '56',
                'spo2' => '99',
                'temperature' => '37.1',
                'diurese' => 'ND',
                'conscience' => 'SO',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'patient arrivé a 07h30 au centre et  installé au B2 ,son dernier repas était a 19h.',
                'periode' => 'preoperatoire',
            ),
            13 => 
            array (
                'id' => '14',
                'user_id' => '12',
                'patient_id' => '85',
                'date' => '2019-11-08',
                'heure' => '09:30',
                'ta' => '142/97',
                'fr' => '18',
                'pouls' => '59',
                'spo2' => '100',
                'temperature' => '36.9',
                'diurese' => 'ND',
                'conscience' => 'SO',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'patient arriver au centre a 8h15 ,installé en salle 103f ,dernier repas a 20h',
                'periode' => 'preoperatoire',
            ),
            14 => 
            array (
                'id' => '15',
                'user_id' => '12',
                'patient_id' => '111',
                'date' => '2019-11-08',
                'heure' => '08:00',
                'ta' => '114/56',
                'fr' => '28',
                'pouls' => '99',
                'spo2' => '100',
                'temperature' => '36.5',
                'diurese' => 'ND',
                'conscience' => 'SO',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'patient recu ce jour pour une intervention. dernier repas a 8h',
                'periode' => 'preoperatoire',
            ),
            15 => 
            array (
                'id' => '16',
                'user_id' => '12',
                'patient_id' => '198',
                'date' => '2019-11-08',
                'heure' => '17:50',
                'ta' => '141/83',
                'fr' => '18',
                'pouls' => '76',
                'spo2' => '98',
                'temperature' => '37.1',
                'diurese' => 'Lavage en cours',
                'conscience' => 'so',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'patient sortie du bloc operatoire a 17h50 etat stable et lavage en cours',
                'periode' => 'postoperatoire',
            ),
            16 => 
            array (
                'id' => '17',
                'user_id' => '12',
                'patient_id' => '198',
                'date' => '2019-11-08',
                'heure' => '17:50',
                'ta' => '141/83',
                'fr' => '18',
                'pouls' => '76',
                'spo2' => '98',
                'temperature' => '36.9',
                'diurese' => 'Lavage en cours',
                'conscience' => 'So',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'patient sortie du bloc operatoire a 17h45 ,stable ,lavage en cours',
                'periode' => 'postoperatoire',
            ),
            17 => 
            array (
                'id' => '18',
                'user_id' => '12',
                'patient_id' => '211',
                'date' => '2019-11-08',
                'heure' => '18:00',
                'ta' => '119/67',
                'fr' => '18',
                'pouls' => '94',
                'spo2' => '97',
                'temperature' => '36.7',
                'diurese' => 'ND',
                'conscience' => 'So',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'patient arrivé au centre a 17h50 
pour une intervention ,instaallé en salle 101p',
                'periode' => 'preoperatoire',
            ),
            18 => 
            array (
                'id' => '19',
                'user_id' => '3',
                'patient_id' => '198',
                'date' => '2019-11-08',
                'heure' => '18:00',
                'ta' => '162/80',
                'fr' => '21',
                'pouls' => '84',
                'spo2' => '98',
                'temperature' => '36.8',
            'diurese' => 'lavage en cours (rosee)',
                'conscience' => 's0',
                'douleur' => 'EVA=4',
                'observation_plainte' => '18h : seringuage .et leger mieux par la suite 
paracetamol 1 g pe os administre PO DR NJINOU',
                'periode' => 'postoperatoire',
            ),
            19 => 
            array (
                'id' => '20',
                'user_id' => '3',
                'patient_id' => '85',
                'date' => '2019-11-08',
                'heure' => '19:00',
                'ta' => '129/90',
                'fr' => '20',
                'pouls' => '76',
                'spo2' => '100',
                'temperature' => '37',
                'diurese' => 'pas de sonde',
                'conscience' => 'so',
                'douleur' => 'eva=1',
                'observation_plainte' => 'pas de plaintes',
                'periode' => 'postoperatoire',
            ),
            20 => 
            array (
                'id' => '21',
                'user_id' => '3',
                'patient_id' => '112',
                'date' => '2019-11-08',
                'heure' => '20:00',
                'ta' => '142/88',
                'fr' => '19',
                'pouls' => '68',
                'spo2' => '99',
                'temperature' => '37',
            'diurese' => '1000CC (v)',
                'conscience' => 'so',
                'douleur' => 'eva=2',
            'observation_plainte' => 'drain =100cc (v)
leger spasme vesical 
paracetamol 500mg   2cp  pris  PO DR NJINOU',
                'periode' => 'postoperatoire',
            ),
            21 => 
            array (
                'id' => '22',
                'user_id' => '3',
                'patient_id' => '211',
                'date' => '2019-11-08',
                'heure' => '19:50',
                'ta' => '130/82',
                'fr' => '18',
                'pouls' => '92',
                'spo2' => '100',
                'temperature' => '37',
                'diurese' => 'pas se sonde',
                'conscience' => 'so',
                'douleur' => 'eva=1',
                'observation_plainte' => 'pas de plaintes',
                'periode' => 'preoperatoire',
            ),
            22 => 
            array (
                'id' => '23',
                'user_id' => '3',
                'patient_id' => '204',
                'date' => '2019-11-08',
                'heure' => '20:00',
                'ta' => '100/60',
                'fr' => '18',
                'pouls' => '64',
                'spo2' => '93',
                'temperature' => '37.2',
            'diurese' => 'lavage en cours (rosee)',
                'conscience' => 'so',
                'douleur' => 'eva=1',
                'observation_plainte' => 'sortie du bloc a 20h24',
                'periode' => 'postoperatoire',
            ),
            23 => 
            array (
                'id' => '24',
                'user_id' => '3',
                'patient_id' => '204',
                'date' => '2019-11-09',
                'heure' => '06:30',
                'ta' => '138/76',
                'fr' => '19',
                'pouls' => '82',
                'spo2' => '98',
                'temperature' => '36.9',
                'diurese' => 'In: 09l       out; 08l',
                'conscience' => 'so',
                'douleur' => 'eva=1',
                'observation_plainte' => 'spasmes
insomnie',
                'periode' => 'postoperatoire',
            ),
            24 => 
            array (
                'id' => '25',
                'user_id' => '3',
                'patient_id' => '198',
                'date' => '2019-11-09',
                'heure' => '06:30',
                'ta' => '122/65',
                'fr' => '20',
                'pouls' => '88',
                'spo2' => '96',
                'temperature' => '36.8',
                'diurese' => 'in: 12l      out: 13l',
                'conscience' => 'so',
                'douleur' => 'eva=1',
                'observation_plainte' => 'dextro : 1.99
pas de plaintes 
stop lavage(rosee)',
                'periode' => 'postoperatoire',
            ),
            25 => 
            array (
                'id' => '26',
                'user_id' => '3',
                'patient_id' => '211',
                'date' => '2019-11-09',
                'heure' => '06:30',
                'ta' => '120/72',
                'fr' => '18',
                'pouls' => '88',
                'spo2' => '100',
                'temperature' => '37',
            'diurese' => '2.5L (v)',
                'conscience' => 'so',
                'douleur' => 'eva=1',
                'observation_plainte' => 'AUCUNE PLAINTE',
                'periode' => 'postoperatoire',
            ),
            26 => 
            array (
                'id' => '27',
                'user_id' => '3',
                'patient_id' => '112',
                'date' => '2019-11-09',
                'heure' => '06:30',
                'ta' => '151/91',
                'fr' => '20',
                'pouls' => '81',
                'spo2' => '100',
                'temperature' => '36.8',
            'diurese' => 'SV 2L(v)',
                'conscience' => 'so',
                'douleur' => 'eva=1',
                'observation_plainte' => 'selles +
gaz+
drain  170cc(hematique) de 24h',
                'periode' => 'postoperatoire',
            ),
            27 => 
            array (
                'id' => '28',
                'user_id' => '12',
                'patient_id' => '204',
                'date' => '2019-11-09',
                'heure' => '15:00',
                'ta' => '131/76',
                'fr' => '18',
                'pouls' => '76',
                'spo2' => '99',
                'temperature' => '38.7',
                'diurese' => 'LAVAGE EN COURS',
                'conscience' => 'So',
                'douleur' => 'EVA:1',
                'observation_plainte' => 'perfangan 1g , nefopam 20mg et ketoprofene 100mg  fait',
                'periode' => 'postoperatoire',
            ),
            28 => 
            array (
                'id' => '29',
                'user_id' => '12',
                'patient_id' => '112',
                'date' => '2019-11-09',
                'heure' => '15:00',
                'ta' => '143/85',
                'fr' => '19',
                'pouls' => '94',
                'spo2' => '99',
                'temperature' => '37',
            'diurese' => 'Su:600cc (v),sv:100cc',
                'conscience' => 'So',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'pas de plainte',
                'periode' => 'postoperatoire',
            ),
            29 => 
            array (
                'id' => '30',
                'user_id' => '12',
                'patient_id' => '198',
                'date' => '2019-11-09',
                'heure' => '13:00',
                'ta' => '159/73',
                'fr' => '19',
                'pouls' => NULL,
                'spo2' => '97',
                'temperature' => '37.3',
            'diurese' => 'Su:1500cc (v),',
                'conscience' => 'So',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'pas de plainte',
                'periode' => 'postoperatoire',
            ),
            30 => 
            array (
                'id' => '31',
                'user_id' => '12',
                'patient_id' => '198',
                'date' => '2019-11-09',
                'heure' => '17:00',
                'ta' => '164/85',
                'fr' => '19',
                'pouls' => '94',
                'spo2' => '98',
                'temperature' => '38.2',
            'diurese' => 'Su:1500cc (v),',
                'conscience' => 'SO',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'Pas de plainte  perfalgan 1g fait',
                'periode' => 'postoperatoire',
            ),
            31 => 
            array (
                'id' => '32',
                'user_id' => '12',
                'patient_id' => '112',
                'date' => '2019-11-09',
                'heure' => '17:30',
                'ta' => '143/85',
                'fr' => '17',
                'pouls' => '99',
                'spo2' => '100',
                'temperature' => '37.7',
                'diurese' => 'SU:650',
                'conscience' => 'So',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'pas de plainte',
                'periode' => 'postoperatoire',
            ),
            32 => 
            array (
                'id' => '33',
                'user_id' => '12',
                'patient_id' => '204',
                'date' => '2019-11-09',
                'heure' => '18:20',
                'ta' => '132/82',
                'fr' => '16',
                'pouls' => '64',
                'spo2' => '97',
                'temperature' => '37.2',
                'diurese' => 'Lavage en cours',
                'conscience' => 'So',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'Pas de plainte',
                'periode' => 'postoperatoire',
            ),
            33 => 
            array (
                'id' => '34',
                'user_id' => '3',
                'patient_id' => '204',
                'date' => '2019-11-10',
                'heure' => '06:30',
                'ta' => '123/74',
                'fr' => '19',
                'pouls' => '76',
                'spo2' => '100',
                'temperature' => '37.1',
            'diurese' => 'in= 4l . out=6l (clair)',
                'conscience' => 'So',
                'douleur' => 'EVA =2',
                'observation_plainte' => 'stop lavage
ketoprofene 100mg per os administre pour dleur 
va mieux ce matin',
                'periode' => 'postoperatoire',
            ),
            34 => 
            array (
                'id' => '35',
                'user_id' => '3',
                'patient_id' => '112',
                'date' => '2019-11-10',
                'heure' => '06:30',
                'ta' => '138/82',
                'fr' => '20',
                'pouls' => '85',
                'spo2' => '99',
                'temperature' => '36.5',
            'diurese' => 'sv= 2l800cc(v) rosee',
                'conscience' => 'So',
                'douleur' => 'EVA =2',
                'observation_plainte' => 'spasme mais tolerable par le patient 
dextro a jeun =2.16g/l
diurese 24h =4l(rose)',
                'periode' => 'postoperatoire',
            ),
            35 => 
            array (
                'id' => '36',
                'user_id' => '3',
                'patient_id' => '198',
                'date' => '2019-11-10',
                'heure' => '06:30',
                'ta' => '174/85',
                'fr' => '20',
                'pouls' => '94',
                'spo2' => '97',
                'temperature' => '37',
                'diurese' => 'in =5.5l    out =7l de 24h',
                'conscience' => 'So',
                'douleur' => 'EVA =2',
                'observation_plainte' => 'leger spasme vesival 
nuit un peu agite 
control TA dans 1 h 
dextro =1.94g/l',
                'periode' => 'postoperatoire',
            ),
            36 => 
            array (
                'id' => '37',
                'user_id' => '6',
                'patient_id' => '104',
                'date' => '2019-11-10',
                'heure' => '12:00',
                'ta' => '149/82',
                'fr' => '23',
                'pouls' => '90',
                'spo2' => '99',
                'temperature' => '39.1',
                'diurese' => '00',
                'conscience' => 'oui',
                'douleur' => 'EVA=0',
                'observation_plainte' => '- paracetamol 1g comprimé pris
- ceftriaxone 2g administrée
- gentamycine 160mg administrée',
                'periode' => 'postoperatoire',
            ),
            37 => 
            array (
                'id' => '38',
                'user_id' => '6',
                'patient_id' => '112',
                'date' => '2019-11-10',
                'heure' => '11:28',
                'ta' => '158/91',
                'fr' => '18',
                'pouls' => '86',
                'spo2' => '98',
                'temperature' => '36.8',
                'diurese' => 'SV: 1000 ml d\'urines rosées vidées',
                'conscience' => 'oui',
                'douleur' => 'EVA=1',
                'observation_plainte' => 'légers spasmes supportables
drain: environ 40ml d\'urines hematiques',
                'periode' => 'postoperatoire',
            ),
            38 => 
            array (
                'id' => '39',
                'user_id' => '6',
                'patient_id' => '198',
                'date' => '2019-11-10',
                'heure' => '12:30',
                'ta' => '160/90',
                'fr' => '18',
                'pouls' => '83',
                'spo2' => '100',
                'temperature' => '36.9',
                'diurese' => 'SV: 300ml',
                'conscience' => 'oui',
                'douleur' => 'EVA=2',
                'observation_plainte' => '10h30: plaintes: spasmes ++ avec présence des caillots de sang dans la tuyauterie de la poche collectrice 
-  decaillotage effectué par Dr DJOUFANG',
                'periode' => 'postoperatoire',
            ),
            39 => 
            array (
                'id' => '40',
                'user_id' => '6',
                'patient_id' => '204',
                'date' => '2019-11-10',
                'heure' => '13:00',
                'ta' => '149/82',
                'fr' => '19',
                'pouls' => '63',
                'spo2' => '99',
                'temperature' => '37.1',
                'diurese' => '800',
                'conscience' => 'oui',
                'douleur' => 'EVA=1',
                'observation_plainte' => 'pas de plaintes exprimées',
                'periode' => 'postoperatoire',
            ),
            40 => 
            array (
                'id' => '41',
                'user_id' => '6',
                'patient_id' => '112',
                'date' => '2019-11-10',
                'heure' => '16:15',
                'ta' => '135/86',
                'fr' => '19',
                'pouls' => '113',
                'spo2' => '95',
                'temperature' => '38.1',
                'diurese' => 'SV: 1000ml d\'urines rosées',
                'conscience' => 'oui',
                'douleur' => 'EVA=0',
                'observation_plainte' => 'drain: eviron 50ml de secretions hematiques 
- lovenox 0.4ui fait en s/c',
                'periode' => 'postoperatoire',
            ),
            41 => 
            array (
                'id' => '42',
                'user_id' => '6',
                'patient_id' => '204',
                'date' => '2019-11-10',
                'heure' => '17:30',
                'ta' => '121/67',
                'fr' => '16',
                'pouls' => '76',
                'spo2' => '98',
                'temperature' => '37.8',
            'diurese' => 'SV: 1400ml d\'urine claire( poche vidée)',
                'conscience' => 'oui',
                'douleur' => 'eva: 0',
                'observation_plainte' => 'plaintes: constipation +++
Macrogol 10g donné PO Dr NJINOU',
                'periode' => 'postoperatoire',
            ),
            42 => 
            array (
                'id' => '43',
                'user_id' => '6',
                'patient_id' => '104',
                'date' => '2019-11-10',
                'heure' => '18:15',
                'ta' => '12070',
                'fr' => '22',
                'pouls' => '88',
                'spo2' => '95',
                'temperature' => '39.1',
                'diurese' => '00',
                'conscience' => 'oui',
                'douleur' => 'EVA: 2',
            'observation_plainte' => 'Plaintes: légères douleurs au niveau de la tête ( l\'occiput) 
CAT: paracetamol 1g inj fait ivdl',
                'periode' => 'postoperatoire',
            ),
            43 => 
            array (
                'id' => '44',
                'user_id' => '8',
                'patient_id' => '204',
                'date' => '2019-11-10',
                'heure' => '22:00',
                'ta' => '128/74',
                'fr' => '17',
                'pouls' => '80',
                'spo2' => '99',
                'temperature' => '36.9',
                'diurese' => '700',
                'conscience' => 'OUI',
                'douleur' => 'EVA:1',
                'observation_plainte' => 'douleur au site -op
para 1g +keto 100mg pris',
                'periode' => 'postoperatoire',
            ),
            44 => 
            array (
                'id' => '45',
                'user_id' => '8',
                'patient_id' => '204',
                'date' => '2019-11-11',
                'heure' => '06:30',
                'ta' => '118/68',
                'fr' => '16',
                'pouls' => '69',
                'spo2' => '99',
                'temperature' => '36.6',
                'diurese' => '1300',
                'conscience' => 'OUI',
                'douleur' => 'EVA:1',
                'observation_plainte' => 'douleur au site-op
selles:ok',
                'periode' => 'postoperatoire',
            ),
            45 => 
            array (
                'id' => '46',
                'user_id' => '8',
                'patient_id' => '112',
                'date' => '2019-11-11',
                'heure' => '06:30',
                'ta' => '145/90',
                'fr' => '18',
                'pouls' => '82',
                'spo2' => '99',
                'temperature' => '36.7',
                'diurese' => 'sv:1800ml   DL:80ml',
                'conscience' => 'OUI',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'nuit calme,pst du drain sale
GAJ:2.33g/l
ditropan5mg pris +ttt perso',
                'periode' => 'postoperatoire',
            ),
            46 => 
            array (
                'id' => '47',
                'user_id' => '8',
                'patient_id' => '198',
                'date' => '2019-11-11',
                'heure' => '06:00',
                'ta' => '161/81',
                'fr' => '18',
                'pouls' => '88',
                'spo2' => '97',
                'temperature' => '36.9',
                'diurese' => '2L',
                'conscience' => 'OUI',
                'douleur' => 'EVA:0',
                'observation_plainte' => 'NUIT CALME
PLAINTES:sensation de decharge electrique dans le membre inferieur gauche depuis la sortie du BO, spasmes 
ditropan 5mg
ttt perso pris(loxen, glucophage',
                    'periode' => 'postoperatoire',
                ),
                47 => 
                array (
                    'id' => '48',
                    'user_id' => '8',
                    'patient_id' => '104',
                    'date' => '2019-11-11',
                    'heure' => '06:30',
                    'ta' => '139/79',
                    'fr' => '18',
                    'pouls' => '76',
                    'spo2' => '97',
                    'temperature' => '37.4',
                    'diurese' => 'N/A',
                    'conscience' => 'OUI',
                    'douleur' => 'EVA:0',
                    'observation_plainte' => 'le 10/11/baisse de la fievre
22h :37.8°C     00H :38°C
Ceftriaxone 2g fait à 00h
ce matin , va mieux',
                    'periode' => 'postoperatoire',
                ),
                48 => 
                array (
                    'id' => '49',
                    'user_id' => '5',
                    'patient_id' => '79',
                    'date' => '2019-11-11',
                    'heure' => '15:00',
                    'ta' => '136/97',
                    'fr' => '18',
                    'pouls' => '70',
                    'spo2' => '97',
                    'temperature' => '36.7',
                    'diurese' => NULL,
                    'conscience' => 'ok',
                    'douleur' => 'EVA=2',
                    'observation_plainte' => 'Légères douleurs au flanc gauche.
CAT: para 1g + spasfon 80 cp administré.',
                    'periode' => 'postoperatoire',
                ),
                49 => 
                array (
                    'id' => '50',
                    'user_id' => '8',
                    'patient_id' => '79',
                    'date' => '2019-11-11',
                    'heure' => '21:00',
                    'ta' => '110/80',
                    'fr' => '16',
                    'pouls' => '88',
                    'spo2' => '97',
                    'temperature' => '37.4',
                    'diurese' => 'N/A',
                    'conscience' => 'OUI',
                    'douleur' => 'EVA:0',
                    'observation_plainte' => 'patient stable
plaintes: brûlures mictionnelles',
                    'periode' => 'postoperatoire',
                ),
                50 => 
                array (
                    'id' => '51',
                    'user_id' => '8',
                    'patient_id' => '79',
                    'date' => '2019-11-12',
                    'heure' => '06:00',
                    'ta' => '136/87',
                    'fr' => '18',
                    'pouls' => '65',
                    'spo2' => '96',
                    'temperature' => '36.8',
                    'diurese' => 'N/A',
                    'conscience' => 'OUI',
                    'douleur' => 'EVA:0',
                    'observation_plainte' => 'nuit calme,
pas de plaintes ce matin',
                    'periode' => 'postoperatoire',
                ),
                51 => 
                array (
                    'id' => '52',
                    'user_id' => '4',
                    'patient_id' => '140',
                    'date' => '2019-11-14',
                    'heure' => '09:25',
                    'ta' => '136/85',
                    'fr' => '18',
                    'pouls' => '82',
                    'spo2' => '98',
                    'temperature' => '36.8',
                    'diurese' => NULL,
                    'conscience' => 'so',
                    'douleur' => 'eva:0',
                'observation_plainte' => 'dernier repas pris à 15h(solide)22h (liquide)',
                    'periode' => 'preoperatoire',
                ),
                52 => 
                array (
                    'id' => '53',
                    'user_id' => '3',
                    'patient_id' => '140',
                    'date' => '2019-11-14',
                    'heure' => '18:30',
                    'ta' => '132/84',
                    'fr' => '20',
                    'pouls' => '92',
                    'spo2' => '97',
                    'temperature' => '37',
                    'diurese' => 'ND',
                    'conscience' => 'So',
                    'douleur' => 'EVA:1',
                    'observation_plainte' => 'sensation de froid reevaluer la temperature corporelle dans 1h',
                    'periode' => 'postoperatoire',
                ),
                53 => 
                array (
                    'id' => '54',
                    'user_id' => '3',
                    'patient_id' => '140',
                    'date' => '2019-11-15',
                    'heure' => '07:00',
                    'ta' => '118/62',
                    'fr' => '18',
                    'pouls' => '80',
                    'spo2' => '99',
                    'temperature' => '37.2',
                    'diurese' => 'ND',
                    'conscience' => 'So',
                    'douleur' => 'EVA:0',
                    'observation_plainte' => 'nuit calme 
pas de plainte 
pansement propre',
                    'periode' => 'postoperatoire',
                ),
                54 => 
                array (
                    'id' => '55',
                    'user_id' => '3',
                    'patient_id' => '247',
                    'date' => '2019-11-16',
                    'heure' => '07:00',
                    'ta' => '148/88',
                    'fr' => '20',
                    'pouls' => '82',
                    'spo2' => '99',
                    'temperature' => NULL,
                'diurese' => 'in= 6l . out=7l (clair)',
                    'conscience' => 'So',
                    'douleur' => 'EVA:0',
                    'observation_plainte' => 'sonde vesical ote ce matin a 6h
miction ok 
nuit calme 
pas de plainte',
                    'periode' => 'postoperatoire',
                ),
                55 => 
                array (
                    'id' => '56',
                    'user_id' => '4',
                    'patient_id' => '225',
                    'date' => '2019-11-18',
                    'heure' => '18:30',
                    'ta' => '148/86mmhg',
                    'fr' => '18',
                    'pouls' => '66',
                    'spo2' => '96',
                    'temperature' => '36.9',
                'diurese' => '1500(vidée)',
                    'conscience' => 'so',
                    'douleur' => '2',
                    'observation_plainte' => 'frissons,douleurs generalisée: temperature 36.9 c.a.t: rechauffeur, para 1g inj  fait.reste en surveillance..',
                    'periode' => 'preoperatoire',
                ),
                56 => 
                array (
                    'id' => '57',
                    'user_id' => '6',
                    'patient_id' => '158',
                    'date' => '2019-11-25',
                    'heure' => '20:00',
                    'ta' => '152/72',
                    'fr' => '20',
                    'pouls' => '64',
                    'spo2' => '100',
                    'temperature' => '36.8',
                    'diurese' => '500 ml d\'urines claires',
                    'conscience' => 'oui',
                    'douleur' => 'EVA=0',
                    'observation_plainte' => 'pas de plaintes exprimées à ce moment, patient connu hypertendu et diabétique sous traitement oraux',
                    'periode' => 'preoperatoire',
                ),
                57 => 
                array (
                    'id' => '58',
                    'user_id' => '6',
                    'patient_id' => '112',
                    'date' => '2019-11-25',
                    'heure' => '19:10',
                    'ta' => '114/52',
                    'fr' => '22',
                    'pouls' => '111',
                    'spo2' => '92',
                    'temperature' => '39.5',
                    'diurese' => 'urines pas quantifieés',
                    'conscience' => 'oui',
                    'douleur' => 'EVA=0',
                    'observation_plainte' => 'patient asthénique et fébrile.
CAT Paracetamol 1g fait ivdl',
                    'periode' => 'postoperatoire',
                ),
                58 => 
                array (
                    'id' => '59',
                    'user_id' => '6',
                    'patient_id' => '112',
                    'date' => '2019-11-26',
                    'heure' => '06:49',
                    'ta' => '123/76',
                    'fr' => '18',
                    'pouls' => '88',
                    'spo2' => '94',
                    'temperature' => '37.8',
                    'diurese' => '00ml',
                    'conscience' => 'oui',
                    'douleur' => 'EVA=0',
                    'observation_plainte' => 'nuit agitée par la survenue exacerbée des fuites d\'urines. pas de plaintes exprimées ce main, contrôle de mieux en mieux les urines',
                    'periode' => 'postoperatoire',
                ),
                59 => 
                array (
                    'id' => '60',
                    'user_id' => '6',
                    'patient_id' => '158',
                    'date' => '2019-11-26',
                    'heure' => '06:16',
                    'ta' => '118/71',
                    'fr' => '16',
                    'pouls' => '70',
                    'spo2' => '98',
                    'temperature' => '63.9',
                    'diurese' => '500 ml d\'urines claires',
                    'conscience' => 'oui',
                    'douleur' => 'EVA=2',
                    'observation_plainte' => 'plaintes: légers spasmes vesicaux intermittents tolérables. GC: 1.21g/l, nuit calme',
                    'periode' => 'preoperatoire',
                ),
                60 => 
                array (
                    'id' => '61',
                    'user_id' => '3',
                    'patient_id' => '112',
                    'date' => '2019-11-27',
                    'heure' => '06:30',
                    'ta' => '130/80',
                    'fr' => '19',
                    'pouls' => '70',
                    'spo2' => '99',
                    'temperature' => '367',
                    'diurese' => 'SV:500cc',
                    'conscience' => 'So',
                    'douleur' => 'EVA =2',
                    'observation_plainte' => '04h :appel pour cephalees + insomnie .administre para 1g cp .
6h:endormi pendant la  prise des parametres
leger mieux ce matin
ATB a administrer des son reveil',
                    'periode' => 'postoperatoire',
                ),
                61 => 
                array (
                    'id' => '62',
                    'user_id' => '3',
                    'patient_id' => '281',
                    'date' => '2019-11-28',
                    'heure' => '06:30',
                    'ta' => '143/77',
                    'fr' => '19',
                    'pouls' => '60',
                    'spo2' => '98',
                    'temperature' => '368',
                    'diurese' => 'ND',
                    'conscience' => 'SO',
                    'douleur' => 'EVA:1',
                    'observation_plainte' => '18h20:leger frisson,T=37 8.
va mieux ce matin ,couleur d urine rosee,dextro=1.49g/l',
                    'periode' => 'postoperatoire',
                ),
            ));
        
        
    }
}