<?php

use Illuminate\Database\Seeder;

class ConsultationsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('consultations')->delete();
        
        \DB::table('consultations')->insert(array (
            0 => 
            array (
                'id' => '4',
                'patient_id' => '22',
                'user_id' => '16',
                'diagnostic' => 'dermatophyties des plis inguinaux',
            'interrogatoire' => 'Evolution des TUBA depuis l\'intervention (TURP en 2016) marquée par
une odeure nauséabonde des urines qui sont moussantes, sans
dysurie, ni impériosités mictionnelle.
se plaint également d\'un prurit des plis inguinaux gênant, surtout
en soirée et ce malgré la prise d\'un traitement prescrit dans notre
structure en 2018 et bien conduit.',
                'antecedent_m' => 'notion d\'infection urinaire en fev 2018 traitée par de l\'amociclav',
                'antecedent_c' => NULL,
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'ordonnance médicale',
                'proposition' => 'Consultation',
                'examen_p' => 'dermatophyties des plis inguinaux',
                'examen_c' => 'ECBU, PSA',
                'motif_c' => 'troubles urinaires du bas appareil
Prurit des organes génitaux externes',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-09-27 12:06:34',
                'updated_at' => '2019-09-27 12:06:34',
                'devis_id' => NULL,
            ),
            1 => 
            array (
                'id' => '5',
                'patient_id' => '23',
                'user_id' => '16',
                'diagnostic' => 'Dysfonction érectile',
                'interrogatoire' => 'DE évoluant depuis près de 6 mois, avec sa seule partenaire,
marquée par une rigidité faible, sans éjaculation précoce.
douleur scrotale peu intense, anxiogène, rare (une fois par
semaine) et frustre.',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'ttt médical',
                'proposition' => 'Consultation',
                'examen_p' => 'OGE d\'aspect normal',
                'examen_c' => 'PSA total
Glycémie
profil lipidique',
                'motif_c' => 'dysfonction érectile 

douleur scrotale gauche',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-09-27 12:36:12',
                'updated_at' => '2019-10-12 17:00:55',
                'devis_id' => '5',
            ),
            2 => 
            array (
                'id' => '6',
                'patient_id' => '62',
                'user_id' => '16',
                'diagnostic' => 'Douleurs scrotales',
                'interrogatoire' => 'evolution depuis un mois; peu gênantes, à type de picotements, sans troubles urinaires du bas appareil.
survenue après un rapport sexuel',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'Levo - Denk 500 mg; Olfen 50 mg',
                'proposition' => 'Consultation',
                'examen_p' => 'discrète pointe herniaire droite, OGE normaux',
                'examen_c' => 'ECBU , PCR Chlamydia',
                'motif_c' => 'douleurs scrotales droites chroniques',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-10-01 12:56:05',
                'updated_at' => '2019-10-01 12:56:05',
                'devis_id' => NULL,
            ),
            3 => 
            array (
                'id' => '8',
                'patient_id' => '69',
                'user_id' => '14',
                'diagnostic' => 'Adénocarcinome prostate localement avancé
Bilan d\'extension par TDM abdomen négatif',
            'interrogatoire' => 'Patient ayant bénéficié en 2018 d\'une série de biopsies de prostate  pour majoration du PSAT à 10,67 et l\'histologie a retrouvé un adénocarcinome de la prostate Gleason 8 (4+4).
Le patient est sous traitement par Décapeptyl 22,5 et Casodex 50.
Injection prise le 30/08/2019.
Il se plaint de bouffées de chaleur.',
                'antecedent_m' => NULL,
                'antecedent_c' => NULL,
                'medecin_r' => 'KAMADJOU Cyril',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'Androcur 50',
                'proposition' => 'Consultation',
                'examen_p' => 'SP',
                'examen_c' => 'Néant',
                'motif_c' => 'Suivi adénocarcinome de la prostate localement avancé.',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-10-02 12:40:57',
                'updated_at' => '2019-10-02 12:40:57',
                'devis_id' => NULL,
            ),
            4 => 
            array (
                'id' => '9',
                'patient_id' => '73',
                'user_id' => '16',
                'diagnostic' => 'vessie neurologique',
            'interrogatoire' => 'Evolution depuis quelques mois (post AVC), d\'une dysurie (jet faible), pollakiurie diurne et  nocturne (2 - 3 levers nocturnes), impériosité mictionnelle (avec fuites) et brulûres mictionnelle gênantes.',
                'antecedent_m' => 'AVC depuis fev 2019, HTA sous ttt',
                'antecedent_c' => NULL,
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'surveillance',
                'proposition' => 'Consultation',
                'examen_p' => 'pas de globe vésical; OGE normaux; Prostate plate de 30 cc.
tonus anal à 2 / 5',
                'examen_c' => 'PSAT , ECBU',
                'motif_c' => 'Troubles urinaires du bas appareil',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-10-03 10:36:36',
                'updated_at' => '2019-10-03 10:36:36',
                'devis_id' => NULL,
            ),
            5 => 
            array (
                'id' => '10',
                'patient_id' => '82',
                'user_id' => '16',
                'diagnostic' => 'RAS',
                'interrogatoire' => 'pas de plainte actuelle; TUBA -; DE  - ;',
            'antecedent_m' => 'Tuméfaction des bourses (non douloureuse) il y\'a 4 mois pour laquelle il a fait de l\'auto - médication.',
                'antecedent_c' => NULL,
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'RAS',
                'proposition' => 'Consultation',
                'examen_p' => 'bon état général, pas de globe vésical; prostate plate au TR. testicules au fond des  bourses d\'aspect normal',
                'examen_c' => 'PSA, ECBU',
                'motif_c' => 'Bilan de contrôle',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-10-04 14:55:50',
                'updated_at' => '2019-10-04 14:55:50',
                'devis_id' => NULL,
            ),
            6 => 
            array (
                'id' => '11',
                'patient_id' => '83',
                'user_id' => '17',
                'diagnostic' => 'Cystite simple',
                'interrogatoire' => 'évolution depuis 3 heures',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'Curetage il y\'a 7 mois',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'Ofloxacine 200',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'ECBU + ATB',
                'motif_c' => 'Hématurie terminale
brûlures mictionnelle',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-10-07 11:55:35',
                'updated_at' => '2019-10-07 11:55:35',
                'devis_id' => NULL,
            ),
            7 => 
            array (
                'id' => '12',
                'patient_id' => '81',
                'user_id' => '17',
            'diagnostic' => 'ADK prostatique Gleason 6(3+3)',
                'interrogatoire' => 'patient suivie en Inde pour Retinite pigmentaire',
                'antecedent_m' => 'Malvoyant',
                'antecedent_c' => 'chirurgie oculaire',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => 'non doc umenté',
                'groupe' => NULL,
                'proposition_therapeutique' => 'RAS',
                'proposition' => 'Actes à réaliser',
                'examen_p' => 'RAS',
                'examen_c' => 'IRM : lésion PIRADS V
PSAt 60.19ng/dl',
                'motif_c' => 'PEC d\'une tumeur prostatique',
                'date_intervention' => '2019-04-20',
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => 'Biopsie prostatique',
                'type_intervention' => NULL,
                'created_at' => '2019-10-07 12:03:44',
                'updated_at' => '2019-11-13 09:10:02',
                'devis_id' => '6',
            ),
            8 => 
            array (
                'id' => '13',
                'patient_id' => '85',
                'user_id' => '17',
                'diagnostic' => 'lithiases rénales et urétérales gauches',
                'interrogatoire' => 'évolution depuis',
                'antecedent_m' => 'HTA +',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'USCO - laser gauche',
                'proposition' => 'Consultation,Consultation d\'anesthésiste',
                'examen_p' => 'RAS',
                'examen_c' => 'URO TDM: lithiases calicielles de 12 et 5 mm gauche 
lithiases urétérales  de 16 et 11 mm  gauche',
                'motif_c' => 'Adressé pour la prise en charge de lithiase rénale gauche',
                'date_intervention' => '0219-10-11',
                'date_consultation' => '2019-10-07',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-10-07 12:54:17',
                'updated_at' => '2019-10-07 12:54:17',
                'devis_id' => NULL,
            ),
            9 => 
            array (
                'id' => '14',
                'patient_id' => '111',
                'user_id' => '13',
                'diagnostic' => 'Uretero-hydronephrose bilatérale d\'origine stenotique des bas uretères',
                'interrogatoire' => 'Pas symptomatique
Apyrétique

Parfois douleurs abdominales',
                'antecedent_m' => NULL,
                'antecedent_c' => 'Ureteroscopie bilatérale récente',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'Sonde double J bilaterale en cas de changement dans la symptomatologie

Prevoir biologie dans 1 mois',
                'proposition' => 'Consultation',
                'examen_p' => 'Normal',
                'examen_c' => 'RAS',
                'motif_c' => 'Suivi de dilatation pyelo-ureterale bilaterale
Rein droit atrophique avec importante dilatation

Creatinine a 7.9 mg/l',
                'date_intervention' => NULL,
                'date_consultation' => '2019-12-07',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-10-12 17:32:52',
                'updated_at' => '2019-10-12 17:51:35',
                'devis_id' => '5',
            ),
            10 => 
            array (
                'id' => '15',
                'patient_id' => '113',
                'user_id' => '13',
                'diagnostic' => 'Hydrocele gauche importante',
                'interrogatoire' => 'Apparition depuis 2 mois d\'une tumefaction scrotale gauche gênante lors du port de sous-vêtements',
                'antecedent_m' => NULL,
            'antecedent_c' => 'Hernie discale opérée deux fois (HG en 1998 et Afrique du sud 2010)

Chirurgie cerebrale',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'Cure d\'hydrocele gauche

Patient Témoin de Jehovah',
                'proposition' => '',
                'examen_p' => 'Importante tuméfaction scrotale gauche de type hydrocele gauche',
                'examen_c' => 'RAS',
                'motif_c' => 'Tumefaction scrotrale gauche gênante',
                'date_intervention' => '2019-11-07',
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-10-12 18:03:42',
                'updated_at' => '2019-10-12 18:04:28',
                'devis_id' => '5',
            ),
            11 => 
            array (
                'id' => '16',
                'patient_id' => '115',
                'user_id' => '13',
                'diagnostic' => 'Récidive sténose urètre

Traitement chirurgical endoscopique par urétrotomie endoscopique',
                'interrogatoire' => 'Jet faible et lent depuis quelques mois
A déjà beneficié d\'uretrotomie endoscopique',
                'antecedent_m' => NULL,
                'antecedent_c' => 'Uretrotomie endoscopique',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'Uretrotomie endoscopique',
                'proposition' => 'Intervention chirurgicale',
                'examen_p' => 'RAS',
                'examen_c' => 'Prevoir débit-metrie',
                'motif_c' => 'Difficultés mictionelles',
                'date_intervention' => '2019-11-07',
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-10-13 10:58:09',
                'updated_at' => '2019-10-13 10:58:09',
                'devis_id' => '5',
            ),
            12 => 
            array (
                'id' => '17',
                'patient_id' => '119',
                'user_id' => '16',
                'diagnostic' => 'sténose de l\'urètre',
            'interrogatoire' => 'dysurie ( jet faible, vidange incomplète), 0 6 2 levers nocturnes évoluant depuis Mars 2019 à la suite de la mise en place d\'une sonde urinaire e n décembre 2019',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'chirurgie',
                'proposition' => 'Intervention chirurgicale',
                'examen_p' => 'miction : jet faible , en un jet',
            'examen_c' => 'UCRM : sténose urétrale entre la jonction pénienne et bulbaire ( 06/ 2019)',
                'motif_c' => 'Troubles urinaires du bas appareil',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-10-14 11:23:44',
                'updated_at' => '2019-10-14 11:23:44',
                'devis_id' => '5',
            ),
            13 => 
            array (
                'id' => '18',
                'patient_id' => '123',
                'user_id' => '17',
                'diagnostic' => 'HBP compliqué hématurie',
                'interrogatoire' => 'évolution depuis 24 h',
                'antecedent_m' => NULL,
                'antecedent_c' => 'TURP en 2015',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'Réhydratation
Levobact 750mg 1cp/j
prevoir PSAt dans mois',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'ECBU  : E. COLI sensible a la Levofloxacine 
PSAt : 22.7 ng/dl',
                'motif_c' => 'Hématurie totale',
                'date_intervention' => NULL,
                'date_consultation' => '2019-12-15',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-04 08:05:21',
                'updated_at' => '2019-11-04 08:27:09',
                'devis_id' => '6',
            ),
            14 => 
            array (
                'id' => '19',
                'patient_id' => '185',
                'user_id' => '17',
                'diagnostic' => 'Uretrite',
                'interrogatoire' => 'évolution depuis 2 semaines au décours d\'un rapport sexuelle non protégé',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'AZithromycine 1g /j pdt 3J
Cipro 750 mg 1cp*2/j pdt 21 JOURS',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'ECBU : stérile
Mycoplasme : positif sensile à Azithromycine et ciprofloxacine 
PU :streptocoques Spp sensible à la cipro 
Chlamydia : positf',
                'motif_c' => 'Picotement urétral 
brûlures mictionnelles',
                'date_intervention' => NULL,
                'date_consultation' => '2019-11-04',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-04 08:32:18',
                'updated_at' => '2019-11-13 09:07:40',
                'devis_id' => '6',
            ),
            15 => 
            array (
                'id' => '20',
                'patient_id' => '134',
                'user_id' => '17',
                'diagnostic' => 'HBP compliqué de RCU',
                'interrogatoire' => 'évolution dépuis 24h',
                'antecedent_m' => 'AVC il y\'a 10 ans sous anti coagulant',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'Sondage transuretrale CH18
Xatral 10 LP
biopsie prostatique',
                'proposition' => 'Intervention chirurgicale',
                'examen_p' => 'Hémiplégie droite',
                'examen_c' => 'PSAt : 19.82 ng/dl   creat : 12.8ng/l
glycémie: 1.42 g/l 
testostérone : 4.44ng/l
ECBU: leucocyturie abacterienne',
                'motif_c' => 'RCU',
                'date_intervention' => '2019-11-04',
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-04 09:02:15',
                'updated_at' => '2019-11-13 09:20:48',
                'devis_id' => '6',
            ),
            16 => 
            array (
                'id' => '21',
                'patient_id' => '189',
                'user_id' => '16',
                'diagnostic' => 'tumeur prostatique',
                'interrogatoire' => 'pas de troubles urinaires du bas appareil; 
libido  nulle (veuf)',
                'antecedent_m' => 'HTA sous amlodipine',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'PSA total',
                'proposition' => 'Consultation',
                'examen_p' => 'prostate bombée de 30 cc',
            'examen_c' => 'PSAT = 11,32  (26 / 02 / 2019) 
Crétininémie = 11,06',
                'motif_c' => 'anomalie du PSA',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-05 14:52:36',
                'updated_at' => '2019-11-05 14:52:36',
                'devis_id' => NULL,
            ),
            17 => 
            array (
                'id' => '22',
                'patient_id' => '112',
                'user_id' => '13',
                'diagnostic' => 'Adénocarcinome prostatique de score 5 selon gleason',
                'interrogatoire' => 'Stable
Explications sur les risques liés à l\'incontinence urinaire transitoire avec la necessité de faire de reeducation perineale et de les risques de dysfonction érectile
Possibilité de faire des injections intra-caverneuses',
                'antecedent_m' => 'Adénocarcinome prostate avec un bilan d\'extension normal',
                'antecedent_c' => NULL,
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'Prostatectomie radicale totale',
                'proposition' => 'Intervention chirurgicale',
                'examen_p' => 'RAS',
                'examen_c' => 'Scanner abdomino-pelvien normal
PSA total  18.28 ng/ml',
                'motif_c' => 'Patient présentant un adénocarcinome prostatique
Discussion des enjeux opératoires',
                'date_intervention' => '2019-11-07',
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => 'Prostatectomie radicale totale',
                'created_at' => '2019-11-06 18:30:29',
                'updated_at' => '2019-11-06 18:30:29',
                'devis_id' => '6',
            ),
            18 => 
            array (
                'id' => '23',
                'patient_id' => '187',
                'user_id' => '13',
            'diagnostic' => 'Hypertrophie prostatique ( 40 cc)',
                'interrogatoire' => 'Suivi prostatique
PSA total 1.96 ng/ml avec un ECBU normal
Urgenturie pouvant occasionner l\'incontinence
Indication de TURP  en 2017 avec lobe Median',
                'antecedent_m' => 'Dysfonction érectile',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'Résection endoscopique bipolaire de prostate programmée en janvier 2020',
                'proposition' => 'Intervention chirurgicale',
                'examen_p' => 'TR Souple hypertrophique, pas de nodule suspect, d\'environ 40 cc',
                'examen_c' => 'PSA total 1.96 ng/ml et ECBU négatif',
                'motif_c' => 'Suivi prostatique',
                'date_intervention' => '2020-01-15',
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
            'type_intervention' => 'Résection endoscopique bipolaire de prostate( Lobe Médian)',
                'created_at' => '2019-11-06 18:45:46',
                'updated_at' => '2019-11-06 18:46:10',
                'devis_id' => '6',
            ),
            19 => 
            array (
                'id' => '24',
                'patient_id' => '156',
                'user_id' => '13',
                'diagnostic' => 'hgjhghfh',
                'interrogatoire' => 'fdfdvgf',
                'antecedent_m' => 'fddggf',
                'antecedent_c' => 'dfggffg',
                'medecin_r' => 'TOUKAM Eve      .',
                'allergie' => NULL,
                'groupe' => 'O+',
                'proposition_therapeutique' => 'fhfghfgh',
                'proposition' => 'Hospitalisation',
                'examen_p' => 'erhythgfh',
                'examen_c' => 'tghgh',
                'motif_c' => 'dvdvdf',
                'date_intervention' => '2019-11-06',
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-06 18:52:55',
                'updated_at' => '2019-11-06 18:52:55',
                'devis_id' => NULL,
            ),
            20 => 
            array (
                'id' => '25',
                'patient_id' => '190',
                'user_id' => '13',
                'diagnostic' => 'Adénocarcinome prostatique de score 9 selon gleason et de stade clinique T4',
                'interrogatoire' => 'Pollakiurie nocturne
Dysurie avec vidange vésicale incomplète
Parfois urgenturie avec mictalgie
Pas d\'hématurie avec un jet urinaire faible',
                'antecedent_m' => 'Problèmes gastriques
HTA sous Amlor',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'Pulpectomie bilatérale avec probable chimiothérapie par Docetaxel ou associée à Zytiga et Prednisolone
Prendre Finasteride 5 mg et prednisolone 5 mg/j et Bicalutamide 50 mg

Explications sur les possibilités thérapeutiques',
                'proposition' => 'Consultation',
                'examen_p' => 'Pas de troisier
TR prostate indurée et nodulaire, d\'environ 50 cc',
                'examen_c' => 'Scanner abdomino-pelvien retrouvant des ganglions iliaques et inter-aortico-cave',
                'motif_c' => 'Patient présentant un adénocarcinome prostatique
PSA total en juillet 2019 à 193 ng/ml et en 2018 à 80.627 ng/ml
Biopsies prostatique avec un gleason 9 ( 5+4) en Aout 2019',
                'date_intervention' => NULL,
                'date_consultation' => '2019-12-15',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-06 19:09:16',
                'updated_at' => '2019-11-06 19:09:16',
                'devis_id' => '6',
            ),
            21 => 
            array (
                'id' => '26',
                'patient_id' => '194',
                'user_id' => '13',
                'diagnostic' => 'Hypertrophie prostatique d\'environ 40 cc',
                'interrogatoire' => 'Mictions fréquentes avec urgenturie
Jet urinaire correct
Pas de mictalgie ni hématurie
Vidange complète
A essayé le Permixon sans amélioration
A bénéficié d\'une fibroscopie qui retrouvait une prostate obstructive',
                'antecedent_m' => 'HTA traitée par Exforge 10/160 mg',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => NULL,
                'groupe' => 'A+',
                'proposition_therapeutique' => 'Remplacer le Permixon par du Xatral lp 10 mg/j',
                'proposition' => 'Consultation',
                'examen_p' => 'TR prostate de consistance souple sans palpation de nodule suspect d\'environ 40 cc',
                'examen_c' => 'Faire PSA total',
                'motif_c' => 'Mictions fréquentes en journée
Pas de Nycturie
Suivi depuis 2018 par le Dr CK',
                'date_intervention' => NULL,
                'date_consultation' => '2019-12-15',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-06 20:03:47',
                'updated_at' => '2019-11-06 20:03:47',
                'devis_id' => '6',
            ),
            22 => 
            array (
                'id' => '27',
                'patient_id' => '195',
                'user_id' => '13',
                'diagnostic' => 'Neuropathies inguino-scrotale gauche',
                'interrogatoire' => 'Sensation de chaleur flanc gauche depuis 7 mois.
Douleur spontanée avec sensation de lourdeur au niveau scrotal gauche depuis chirurgie de hernie inguinale gauche par Prof SYLLA au Sénégal  en 2008. 
Pas de bilan réalisé',
                'antecedent_m' => 'Azoospermie',
                'antecedent_c' => 'Cure de hernie inguinale gauche en 2008',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => 'RAS',
                'groupe' => 'O+',
                'proposition_therapeutique' => 'LAroxyl gouttes 3-3-6 par jour',
                'proposition' => 'Consultation',
                'examen_p' => 'Testicules normaux
Pas d\'objectivation de lésion ou masse particulière',
                'examen_c' => 'RAS',
                'motif_c' => 'Douleurs flanc gauche',
                'date_intervention' => NULL,
                'date_consultation' => '2019-12-15',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-06 20:14:29',
                'updated_at' => '2019-11-06 20:14:29',
                'devis_id' => '6',
            ),
            23 => 
            array (
                'id' => '28',
                'patient_id' => '104',
                'user_id' => '13',
                'diagnostic' => 'Hypertrophie prostatique avec un PSA total à 8.87 ng/ml avec ratio à 35%',
                'interrogatoire' => 'Suivi prostatique depuis 2010 sous Xatral lp 10 mg
Augmentation des PSA en 2013 puis mis sous Xatral et Avodart
En 2016 IRM avec volume de 70 cc
Mictions en petites quantités et en deux temps
Besoin mictionnel frequent avec rétention urinaire ( SV ramenant 1250 cc)',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'biopsies de prostate dous sédation',
                'proposition' => 'Intervention chirurgicale',
                'examen_p' => 'TR ferme prostate de  90 cc',
                'examen_c' => 'IRM 2016 avec zones PIRADS 4',
                'motif_c' => 'Augmentation anormale des PSA',
                'date_intervention' => '2019-11-07',
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => 'Biopsies de prostate sous sédation',
                'created_at' => '2019-11-07 13:08:21',
                'updated_at' => '2019-11-07 13:08:21',
                'devis_id' => '6',
            ),
            24 => 
            array (
                'id' => '29',
                'patient_id' => '203',
                'user_id' => '13',
                'diagnostic' => 'Infection urinaire infra-clinique',
                'interrogatoire' => 'A noté sur ECBU des 14/10 et 31/10 un E. Coli 10X5 et 10X3 respectivement',
                'antecedent_m' => NULL,
                'antecedent_c' => 'Pelvectomie antérieure avec dérivation urinaire selon Bricker',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'Acidification urinaire et tres bonne hydratation',
                'proposition' => 'Consultation',
                'examen_p' => 'Normal',
                'examen_c' => 'Echographie rénale ne retrouvant aucune dilatation pyélo-urétérale',
                'motif_c' => 'Infections urinaires à répétition',
                'date_intervention' => NULL,
                'date_consultation' => '2020-01-15',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-07 13:28:40',
                'updated_at' => '2019-11-07 13:28:40',
                'devis_id' => '6',
            ),
            25 => 
            array (
                'id' => '30',
                'patient_id' => '208',
                'user_id' => '13',
                'diagnostic' => 'Rétention urinaire avec sonde à demeure',
                'interrogatoire' => 'Chute a domicile mi-octobre 2019
Chirurgie cranienne et sonde à demeure mi-octobre 2019 ( 21/10/2019)
Douleurs pelvi-périnéales
Est sous Zoladex trimestriel',
                'antecedent_m' => 'Adénocarcinome de prostate',
                'antecedent_c' => 'Résection palliative de la prostate
Pulpectomie bilatérale
Chirurgie cranienne',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'Changement sonde à demeure 
Faire scanner pelvien
Poursuite Levofloxacine 500 mg /j pendant 10 jours
Xtandi 4 cp /j pendant 5 jours',
                'proposition' => 'Consultation',
                'examen_p' => 'Sonde à demeure
Le TR retrouve une douleur prostatique à la palpation',
                'examen_c' => 'RAS',
                'motif_c' => 'Rétention urinaire post Hématome cerebral',
                'date_intervention' => NULL,
                'date_consultation' => '2019-12-15',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-07 16:34:49',
                'updated_at' => '2019-11-07 16:43:10',
                'devis_id' => '6',
            ),
            26 => 
            array (
                'id' => '31',
                'patient_id' => '202',
                'user_id' => '13',
                'diagnostic' => 'Lithiase urinaire gauche',
                'interrogatoire' => 'Hématurie macroscopique
Difficultés mictionnelles
Crise de colique néphrétique gauche en mai 2018',
                'antecedent_m' => 'Calculs urinaires',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'Traitement antalgique
Faire un scanner abdomino-pelvien',
                'proposition' => 'Consultation',
                'examen_p' => 'Nihil',
                'examen_c' => 'Scanner abdomino-pelvien retrouvant en 2018 un calcul de la jonction pyélo-urétérale gauche',
                'motif_c' => 'Lithiase appareil urinaire gauche
Problème de miction',
                'date_intervention' => NULL,
                'date_consultation' => '2019-11-08',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-07 17:09:42',
                'updated_at' => '2019-11-07 17:11:32',
                'devis_id' => '6',
            ),
            27 => 
            array (
                'id' => '32',
                'patient_id' => '211',
                'user_id' => '13',
                'diagnostic' => 'CAlculs reins droit et gauche et uretère iliaque droit et méat gauche',
                'interrogatoire' => 'Douleurs lombaires bilatérales
Calculs appareil urinaire droit et gauche connu',
                'antecedent_m' => 'Ulcuc gastrique avec anémie et transfusion récente',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'Urétéroscopie bilatérale et sonde double J bilatérale 
Programmation Urétéroscopie bilatérale laser',
                'proposition' => 'Intervention chirurgicale',
                'examen_p' => 'Correct',
                'examen_c' => 'Echographie abdominale retrouvant des calculs de 25 mm calice superieur rein droit, calculs rein gauche et calculs méat gauche de 10 mm et uretère iliaque droit de 24 mm',
                'motif_c' => 'Crise de colique néphrétique bilatérale
Patient vu en consultation en Mai 2018',
                'date_intervention' => '2019-11-09',
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => 'Urétéroscopie bilatérale  et sondes double J bilatérale',
                'created_at' => '2019-11-08 14:42:53',
                'updated_at' => '2019-11-08 14:42:53',
                'devis_id' => '6',
            ),
            28 => 
            array (
                'id' => '33',
                'patient_id' => '236',
                'user_id' => '17',
                'diagnostic' => 'traumatisme de l’urètre',
                'interrogatoire' => 'évolution depuis 3 heures post coital',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'Boncipro 750 mg',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'RAS',
                'motif_c' => 'hematurie initiale',
                'date_intervention' => NULL,
                'date_consultation' => '2019-11-12',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-12 15:32:55',
                'updated_at' => '2019-11-12 15:32:55',
                'devis_id' => '6',
            ),
            29 => 
            array (
                'id' => '34',
                'patient_id' => '231',
                'user_id' => '17',
                'diagnostic' => 'D.E',
                'interrogatoire' => 'Evolution dépuis 2ans',
                'antecedent_m' => 'Sérologie VIH +',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'Megalis 20mg  1cp * /3j
Procomil 5 mg 1cp*3/j
ARRET megalis 
melex
erector 50',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'Testostérone: 10 ng/dl
Prolactine 4.06 ng/ml',
                'motif_c' => 'DE defaut de rigidité + éjaculation précoce',
                'date_intervention' => NULL,
                'date_consultation' => '2019-11-12',
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-13 08:51:43',
                'updated_at' => '2019-11-27 09:11:46',
                'devis_id' => '6',
            ),
            30 => 
            array (
                'id' => '35',
                'patient_id' => '205',
                'user_id' => '17',
                'diagnostic' => 'D.E',
                'interrogatoire' => 'evolution dépuis 15 ans',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'Psychothérapie',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'RAS',
                'motif_c' => 'D.E : Ejaculation Précoce',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-13 09:13:33',
                'updated_at' => '2019-11-13 09:13:33',
                'devis_id' => '6',
            ),
            31 => 
            array (
                'id' => '36',
                'patient_id' => '200',
                'user_id' => '17',
                'diagnostic' => 'Neuropathie Diabétique',
                'interrogatoire' => 'Evolution depuis 9 mois',
                'antecedent_m' => 'Diabétique suivie',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => 'RAS',
                'groupe' => NULL,
                'proposition_therapeutique' => 'consultation diabétologue',
                'proposition' => 'Consultation',
                'examen_p' => 'Obésité ++++',
                'examen_c' => 'RAS',
                'motif_c' => 'Névralgie diffuse',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-13 09:17:49',
                'updated_at' => '2019-11-13 09:17:49',
                'devis_id' => '6',
            ),
            32 => 
            array (
                'id' => '37',
                'patient_id' => '246',
                'user_id' => '16',
                'diagnostic' => 'probable tumeur vésicale secondaire',
                'interrogatoire' => 'évolution depuis 2 semaines, terminales, avec parfois bbeaucoup de caillots, associée à des douleurs pelviennes très intenses, sans autres TUBA.',
                'antecedent_m' => NULL,
            'antecedent_c' => 'suivi à l\'hopital général pour tumeur du côlon pour laquelle elle a subi une colectomie après 7 séances de chimiothérapie; et une métastasectomie hépatique (il y\'a un an).',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'cystoscopie',
                'proposition' => 'Actes à réaliser',
                'examen_p' => 'assez bon état général, ECOG à 2 / 4; pas de masse abdominale palpée',
                'examen_c' => 'ECho AU : probable tumeur vésicale',
                'motif_c' => 'hématurie',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => 'Cystoscopie',
                'type_intervention' => NULL,
                'created_at' => '2019-11-14 11:29:50',
                'updated_at' => '2019-11-14 11:29:50',
                'devis_id' => NULL,
            ),
            33 => 
            array (
                'id' => '38',
                'patient_id' => '253',
                'user_id' => '16',
                'diagnostic' => 'DE',
                'interrogatoire' => 'Evolution depuis 6 mois , avec toutes ses partenaires; érections matinales +; dépression récentes;
EP avec IELT < 5 min parfois  ; 2 ème ES difficile
TUBA : PKN (2LN) , brulûres mictionnelles',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'envisager IPDE5',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'ECBU, PCR Clamydia,',
                'motif_c' => 'DE, "sperme acide"',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-18 08:42:57',
                'updated_at' => '2019-11-18 08:53:44',
                'devis_id' => '6',
            ),
            34 => 
            array (
                'id' => '39',
                'patient_id' => '255',
                'user_id' => '16',
                'diagnostic' => '# prostatite chronique
colopathie fonctionnelle suspectée',
                'interrogatoire' => 'Evolution depuis un an, par intermittence, intense, non insomniantes; calmées par la miction, sans autres TUBA.
associées à une DE lors des douleurs.',
                'antecedent_m' => 'notion de calcul vésical vu lors d\'une écho AU de juin 2019',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => '# Levofloxaxine + Olfen',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'Echo AU; ECBU',
                'motif_c' => 'Douleur hypogastrique chronique',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-18 09:16:24',
                'updated_at' => '2019-11-18 09:16:24',
                'devis_id' => '6',
            ),
            35 => 
            array (
                'id' => '40',
                'patient_id' => '256',
                'user_id' => '16',
                'diagnostic' => '# herpès génital',
                'interrogatoire' => 'evolution depuis une semaines, début par un prurit de la verge puis apparition de 4 boutons au niveau du gland et près du frein, sans troubles urinaire du bas appareil, ni écoulement urétral.
un épisode similaire il y\'a 6 mois.
pas de notion de RS à risque récent
Actuellement sous Zovirax',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'Doxycyclines',
                'proposition' => 'Consultation',
                'examen_p' => 'plaie pénienne ventrale près du frein, très douloureuse au toucher',
                'examen_c' => 'Sérologie herpes, chlamydia',
                'motif_c' => 'lésions cutanées au niveau de la verge',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-18 09:51:33',
                'updated_at' => '2019-11-18 09:51:33',
                'devis_id' => '6',
            ),
            36 => 
            array (
                'id' => '41',
                'patient_id' => '225',
                'user_id' => '16',
                'diagnostic' => 'prostatite aigue',
                'interrogatoire' => 'Evolution depuis 5 jours, après une cystoscopie faite au centre 3 jours avant.
présente par ailleurs une accentuation des  troubles urinaires du bas appareil (dysurie ++) malgré la prise depuis 3 jours d\'Oflocet 200mg / 12 h et Xatral 10mg/24 h.',
                'antecedent_m' => NULL,
                'antecedent_c' => NULL,
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'antibiothérapie',
                'proposition' => 'Hospitalisation',
                'examen_p' => 'RAS',
                'examen_c' => 'RAS',
                'motif_c' => 'Syndrome infectieux',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-18 10:47:12',
                'updated_at' => '2019-11-18 10:47:12',
                'devis_id' => '6',
            ),
            37 => 
            array (
                'id' => '42',
                'patient_id' => '257',
                'user_id' => '17',
                'diagnostic' => 'Infection urinaire',
                'interrogatoire' => 'évolution depuis 1 mois',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => 'ras',
                'groupe' => NULL,
                'proposition_therapeutique' => 'observation',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'ECBU',
                'motif_c' => 'urine Mousseuse',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-18 14:04:01',
                'updated_at' => '2019-11-18 14:04:01',
                'devis_id' => '6',
            ),
            38 => 
            array (
                'id' => '43',
                'patient_id' => '259',
                'user_id' => '16',
                'diagnostic' => 'DE',
                'interrogatoire' => 'Evolution depuis plusierurs années; 2 / 10 RSS; IELT < 5 min; érection matinale + ; Stress + ; Dépression - ;
TUBA : dysurie - ; pollakiurie diurne avec une miction par heure ( traitée par du  TOVIAZ); impériosité mictionnelle -',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'bilan sanguin',
                'proposition' => 'Consultation',
                'examen_p' => 'Hydrocèle droite moyenne abondance; OGE d\'aspect normal',
                'examen_c' => '-',
                'motif_c' => 'Dysfonction érectile 
Ejaculation précoce',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-22 09:18:07',
                'updated_at' => '2019-11-22 09:18:07',
                'devis_id' => '6',
            ),
            39 => 
            array (
                'id' => '44',
                'patient_id' => '262',
                'user_id' => '16',
                'diagnostic' => 'DE',
                'interrogatoire' => 'Evolution depuis 1 an et demi; avec toutes ses partenaires, rigidité faible, érections matinales +; 2 / 10 rapports sexuels satisfaisants;
pas de UBA gênants, en dehors d\'un jet urinaires moyen
pas de troubles psychologiques; pas d\'éjaculation',
                'antecedent_m' => 'Diabétique sous Metformine; alcool - ; tabac -',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'bilan',
                'proposition' => 'Consultation',
                'examen_p' => 'OGE normaux, prostate plate de 30 cc',
                'examen_c' => 'bilan sanguin, débitmétrie',
                'motif_c' => 'DE',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-22 15:47:47',
                'updated_at' => '2019-11-22 15:47:47',
                'devis_id' => '6',
            ),
            40 => 
            array (
                'id' => '45',
                'patient_id' => '248',
                'user_id' => '17',
                'diagnostic' => 'GG inguinaux',
                'interrogatoire' => 'evoltion depuis environ 1 an',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'HIDte il ya 2 ans',
                'medecin_r' => 'DJOUFANG Rodrigue',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'Ketonal 100 mg',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'PSAt: 1.8ng/dl  
ECBU: Sterile 
Echo inguinales  :testicules normaux; varicocèle gauche ; gg inguinaus bil',
                'motif_c' => 'Algie inguinales gauches',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-25 11:26:34',
                'updated_at' => '2019-11-25 11:26:34',
                'devis_id' => '6',
            ),
            41 => 
            array (
                'id' => '46',
                'patient_id' => '274',
                'user_id' => '16',
                'diagnostic' => 'Ejaculation précoce',
                'interrogatoire' => 'Evolution depuis un an, avec toutes ses partenairees; IELT < 1 min; sans DE',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'Ras',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'Deroxat 20 mg + Rigide 50 mg',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'RAS',
                'motif_c' => 'Ejaculation précoce',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-25 12:26:20',
                'updated_at' => '2019-11-25 12:26:20',
                'devis_id' => '6',
            ),
            42 => 
            array (
                'id' => '47',
                'patient_id' => '283',
                'user_id' => '16',
                'diagnostic' => 'bilan',
                'interrogatoire' => 'pas de plaintes urinaires',
                'antecedent_m' => 'RAS',
                'antecedent_c' => 'RAS',
                'medecin_r' => 'KUITCHE Jerry',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'en attentee',
                'proposition' => 'Consultation',
                'examen_p' => 'RAS',
                'examen_c' => 'ECBU, PSAT, PCR chlamydia/ gonococcie, Glycémie;
Echo arbre urinaire; débitmétrie',
                'motif_c' => 'Bilan de contrôle',
                'date_intervention' => NULL,
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-27 15:38:45',
                'updated_at' => '2019-11-27 15:38:45',
                'devis_id' => '6',
            ),
            43 => 
            array (
                'id' => '48',
                'patient_id' => '285',
                'user_id' => '13',
                'diagnostic' => 'RAS',
                'interrogatoire' => 'Mauvaise alimentation',
                'antecedent_m' => NULL,
                'antecedent_c' => NULL,
                'medecin_r' => 'NJINOU NGNINKEU Bertin',
                'allergie' => NULL,
                'groupe' => NULL,
                'proposition_therapeutique' => 'RAS',
                'proposition' => 'Hospitalisation',
                'examen_p' => 'RAS',
                'examen_c' => 'RAS',
                'motif_c' => 'Malaise inattendu',
                'date_intervention' => '2019-11-29',
                'date_consultation' => NULL,
                'date_consultation_anesthesiste' => NULL,
                'acte' => '',
                'type_intervention' => NULL,
                'created_at' => '2019-11-29 17:22:37',
                'updated_at' => '2019-11-29 17:23:10',
                'devis_id' => '6',
            ),
        ));
        
        
    }
}