<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => '1',
                'name' => 'KOUAMO',
                'prenom' => 'Stephane',
                'login' => 'Administrateur',
                'telephone' => '24597903',
                'sexe' => 'homme',
                'lieu_naissance' => 'Mbouda',
                'date_naissance' => '1990-01-01 16:48:39',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$CX/2/65B62a15LHtEDATu.ESqxd8sqpcCGgG1hMLSfbI950GxB0sq',
                'remember_token' => '5v6uoTO8xdDC7uNuZqIQLS0ItzuFDFIPB2aDaO4mHXm4af9w7TCjTiScQ3YP',
                'created_at' => '2019-09-26 16:48:39',
                'updated_at' => '2019-09-26 16:48:39',
                'role_id' => '1',
            ),
            1 => 
            array (
                'id' => '2',
                'name' => 'MOUSSINGA',
                'prenom' => 'GENEVIEVE',
                'login' => 'GENEVIEVE',
                'telephone' => '694573129',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1979-01-03 16:48:39',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$DSzejx0MyrSvMy81GMFf9eyoSWKdFaNDCCZju239G5.cCNJkyDxiu',
                'remember_token' => NULL,
                'created_at' => '2019-09-26 16:48:40',
                'updated_at' => '2019-09-26 16:48:40',
                'role_id' => '8',
            ),
            2 => 
            array (
                'id' => '3',
                'name' => 'TOMDIO',
                'prenom' => 'PRISCA',
                'login' => 'TOMDIO',
                'telephone' => '654275011',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1985-10-05 16:48:40',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$2HTmZzB6dhoK8qSqd4gZFOFbXpqbTZvOQ7Gl0Bf8jiCuJNtqQW90W',
                'remember_token' => 'YD0Uj25lKDk3ux5OgKFbQ0nb9qjSwHgbjZNG1mpDJoPYe21m1Qz8sINXzYRt',
                'created_at' => '2019-09-26 16:48:40',
                'updated_at' => '2019-09-26 16:48:40',
                'role_id' => '4',
            ),
            3 => 
            array (
                'id' => '4',
                'name' => 'NOCHI FOUODJI',
                'prenom' => 'Edith',
                'login' => 'NOCHI FOUODJI',
                'telephone' => '654275251',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1985-10-05 16:48:40',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$iUY2UPJNLFI9NmG3AacyHOXq2JF0jJ4sxAeDyV2LpHuGRsiWiezd6',
                'remember_token' => 'E8yJp71G2mcqnQanKih7JZGSciJYSL8fxxFs1FcpdirtBPWBhgA6Ia94Y69o',
                'created_at' => '2019-09-26 16:48:40',
                'updated_at' => '2019-09-26 16:48:40',
                'role_id' => '4',
            ),
            4 => 
            array (
                'id' => '5',
                'name' => 'DEMGNE',
                'prenom' => 'VIVIANE',
                'login' => 'VIVIANE',
                'telephone' => '694259512',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Yaounde',
                'date_naissance' => '1989-05-28 16:48:40',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$UbW1zk0CrsxeI3ZBto/wX.NlXOPgkl4rxK7k/wv4d41A/tikWJwPy',
                'remember_token' => 'IGZ22PsUmKTRhkkgxnFme56POvobn6GCzahLK3nzlGIqhrTo7cWbKGtLBLy5',
                'created_at' => '2019-09-26 16:48:40',
                'updated_at' => '2019-09-26 16:48:40',
                'role_id' => '4',
            ),
            5 => 
            array (
                'id' => '6',
                'name' => 'NGUMNJUEN',
                'prenom' => 'MOREEN',
                'login' => 'MOREEN',
                'telephone' => '673013211',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1987-12-31 16:48:41',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$jayzR9UY8Hlc2ytCN7XdkepCPcC4GFbBZVqwmClgpe.3U055iL3.6',
                'remember_token' => NULL,
                'created_at' => '2019-09-26 16:48:41',
                'updated_at' => '2019-09-26 16:48:41',
                'role_id' => '4',
            ),
            6 => 
            array (
                'id' => '7',
                'name' => 'NOUGWAPI',
                'prenom' => 'SORELLE',
                'login' => 'SORELLE',
                'telephone' => '673013201',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1983-03-26 16:48:41',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$OB8JsjTfdiwN.XFpYObs2OVz8m47JIIHMK8MCCC3KU1jkNSQLmX4C',
                'remember_token' => NULL,
                'created_at' => '2019-09-26 16:48:41',
                'updated_at' => '2019-09-26 16:48:41',
                'role_id' => '4',
            ),
            7 => 
            array (
                'id' => '8',
                'name' => 'NKANKO',
                'prenom' => 'LYNDA',
                'login' => 'NKANKO',
                'telephone' => '670014098',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Bafoussam',
                'date_naissance' => '1990-06-13 16:48:41',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$nx/NBlEUCAD7meLVJncdj.rr6g0EspG6KooU2GLAyx3u1kM6KO8ji',
                'remember_token' => 'eWbWrI4PmLY5xsHaBdAvO0tEYF7Zb60nTMBaQkNk1NiuA1d0n6NGTtMgU7ck',
                'created_at' => '2019-09-26 16:48:41',
                'updated_at' => '2019-09-26 16:48:41',
                'role_id' => '4',
            ),
            8 => 
            array (
                'id' => '9',
                'name' => 'TOUDJEU',
                'prenom' => 'RAÏSSA',
                'login' => 'TOUDJEU',
                'telephone' => '656635252',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1994-03-02 16:48:41',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$twJNF6GugVRSRTZLa9ZAN.IguN8cpa7GExmz6BtRy8R1qjWfzrdY.',
                'remember_token' => 'Wwj2SI3fwYNltlbJsyCwRqjL2mKbgoSpCZvMqPhXOnla1b5oOGrirljuwtVv',
                'created_at' => '2019-09-26 16:48:42',
                'updated_at' => '2019-09-26 16:48:42',
                'role_id' => '4',
            ),
            9 => 
            array (
                'id' => '10',
                'name' => 'NANA',
                'prenom' => 'DOMINIQUE',
                'login' => 'DOMINIQUE',
                'telephone' => '677761482',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Yaounde',
                'date_naissance' => '1990-01-11 16:48:42',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$bhbp5.kWOL3VkWZdyp/Pu.FRoNWheZjU/H7sp3WTmZGugddfrTqTO',
                'remember_token' => 'Ytd5LYeypP5ZZl3KLqIrESypBgSrAXNxGil8vJr4nugbQGJT5zRNGVm0sgrS',
                'created_at' => '2019-09-26 16:48:42',
                'updated_at' => '2019-09-26 16:48:42',
                'role_id' => '4',
            ),
            10 => 
            array (
                'id' => '11',
                'name' => 'NGUMNJUEN',
                'prenom' => 'MOREEN',
                'login' => 'NGUMNJUEN',
                'telephone' => '673013200',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Njisse',
                'date_naissance' => '1985-05-28 16:48:42',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$Tg9HQVmKmga0JkiyDlVGpO2GtQi9KXB.k4R68mOF.pYOXbMxZbvWK',
                'remember_token' => '6GUl5wMKby0w8P9IqRuECEJZHr85wZnJBtOAYDfbZALa3vFkNmbNNs9zHczk',
                'created_at' => '2019-09-26 16:48:42',
                'updated_at' => '2019-09-26 16:48:42',
                'role_id' => '4',
            ),
            11 => 
            array (
                'id' => '12',
                'name' => 'SEUTIO TCHOUBI',
                'prenom' => 'ROMEO',
                'login' => 'SEUTIO',
                'telephone' => '694546170',
                'sexe' => 'Masculin',
                'lieu_naissance' => 'Njisse',
                'date_naissance' => '1985-05-28 16:48:42',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$wMIZyc8vwy78jtqtifR9buzENns51LEfdPV0msRI0e4GOwhO6Ocsq',
                'remember_token' => 'josov3hkIrYG89so9MqI62GPqKoPifR1RY76TcqK6QP5NvWokE4DWHiucoyc',
                'created_at' => '2019-09-26 16:48:42',
                'updated_at' => '2019-09-26 16:48:42',
                'role_id' => '4',
            ),
            12 => 
            array (
                'id' => '13',
                'name' => 'NJINOU NGNINKEU',
                'prenom' => 'Bertin',
                'login' => 'NJINOU',
                'telephone' => '40677785',
                'sexe' => 'Masculin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1990-01-01 16:48:43',
                'specialite' => 'Chirurgien urologue',
                'onmc' => '5531',
                'password' => '$2y$10$fZYlzxnSJVU5rarhiN.hoe4FjxkDcCaxxUESMunYzpnZjy6brujlK',
                'remember_token' => 'F6kppCEtR1KVnXelnVIZhxOLDfeMVAcOf2Cv4jiDuj4Ywry6pEIlEBw9HHsb',
                'created_at' => '2019-09-26 16:48:43',
                'updated_at' => '2019-09-26 16:48:43',
                'role_id' => '2',
            ),
            13 => 
            array (
                'id' => '14',
                'name' => 'KAMADJOU',
                'prenom' => 'Cyril',
                'login' => 'KAMADJOU',
                'telephone' => '75569465',
                'sexe' => 'Masculin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1990-01-01 16:48:43',
                'specialite' => 'Chirurgien urologue',
                'onmc' => '0000',
                'password' => '$2y$10$vI2K.usGjqV6n8XhUZNnQuB.yaS0hlb0Ovz4w8x1L0BDbts7nO5zK',
                'remember_token' => 'bEQuDHjnV6rLBS0FsR4EyGPOS0pkd8RHOxbEOdB2UznaHn3YMk5kZjhURBJC',
                'created_at' => '2019-09-26 16:48:43',
                'updated_at' => '2019-09-26 16:48:43',
                'role_id' => '2',
            ),
            14 => 
            array (
                'id' => '15',
                'name' => 'TENKE',
                'prenom' => 'Christelle',
                'login' => 'TENKE',
                'telephone' => '71464734',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1990-01-01 16:48:43',
                'specialite' => 'Anesthésiste',
                'onmc' => '0000',
                'password' => '$2y$10$8ABaLCLigHvcLibPIDyy0uXWrwMzh8YcU8xdUBfMMuIE6SrwAblCi',
                'remember_token' => 'cC9JnxFhSp7sy7FVjdWbm35okwWRNIBibmvnTSyzqsa0zqaup99uy8YzzOmG',
                'created_at' => '2019-09-26 16:48:43',
                'updated_at' => '2019-09-26 16:48:43',
                'role_id' => '2',
            ),
            15 => 
            array (
                'id' => '16',
                'name' => 'KUITCHE',
                'prenom' => 'Jerry',
                'login' => 'KUITCHE',
                'telephone' => '48895244',
                'sexe' => 'Masculin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1990-01-01 16:48:44',
                'specialite' => 'Chirurgien urologue',
                'onmc' => '7858',
                'password' => '$2y$10$FL8cd4Pkx4qytXIQ8bzXve2M3op7ky8MYLm5TmW34VlygU3pqSDAq',
                'remember_token' => '3ZfTZanM8e9J5VQkb4naslHjUCTk2lX5eMZ7qBtS11TuMu3tVAxdffgIXDzB',
                'created_at' => '2019-09-26 16:48:44',
                'updated_at' => '2019-09-26 16:48:44',
                'role_id' => '2',
            ),
            16 => 
            array (
                'id' => '17',
                'name' => 'NGAPNA',
                'prenom' => 'Yves',
                'login' => 'NGAPNA',
                'telephone' => '41016656',
                'sexe' => 'Masculin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1990-01-01 16:48:44',
                'specialite' => 'Chirurgien urologue',
                'onmc' => '0000',
                'password' => '$2y$10$/waG5KwlC3BBmWUYPsPX7.6CImY8OVYyQUgFPTK87Vhj6zGqr3ZhG',
                'remember_token' => 'a0630n2xXQ3hXpkvLIzpaBP1ChhD8pMQ2xw133fPYTNQRIhUQtZjwnyK7Xhs',
                'created_at' => '2019-09-26 16:48:44',
                'updated_at' => '2019-09-26 16:48:44',
                'role_id' => '2',
            ),
            17 => 
            array (
                'id' => '18',
                'name' => 'MAKON',
                'prenom' => 'Stéphane',
                'login' => 'MAKON',
                'telephone' => '20502441',
                'sexe' => 'Masculin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1990-01-01 16:48:44',
                'specialite' => 'Chirurgien urologue',
                'onmc' => '0000',
                'password' => '$2y$10$B0nrmroya96vSTRDqE.gYOjRfBCoZ6.KoXxjDmG/7YV/eAcgBsbUS',
                'remember_token' => NULL,
                'created_at' => '2019-09-26 16:48:44',
                'updated_at' => '2019-09-26 16:48:44',
                'role_id' => '2',
            ),
            18 => 
            array (
                'id' => '19',
                'name' => 'NGANDEU',
                'prenom' => 'Marcel Jerry',
                'login' => 'NGANDEU',
                'telephone' => '27223391',
                'sexe' => 'Masculin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1990-01-01 16:48:44',
                'specialite' => 'Chirurgien urologue',
                'onmc' => '0000',
                'password' => '$2y$10$gRslZC52tMvm35DORKurc.xdgCaa256Mg0RVaaIh9m9hzi4lyCPea',
                'remember_token' => 'Q5pHgjk18XMAiATbtfXzZpTkNn6g0CnsxFqIoHYcRRdBEhtU252Ijp2dNTi0',
                'created_at' => '2019-09-26 16:48:45',
                'updated_at' => '2019-09-26 16:48:45',
                'role_id' => '2',
            ),
            19 => 
            array (
                'id' => '20',
                'name' => 'NTEHJOUEN',
                'prenom' => 'Aminatou',
                'login' => 'NTEHJOUEN',
                'telephone' => '55734739',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Foumbot',
                'date_naissance' => '1984-11-30 16:48:45',
                'specialite' => 'Médecin généraliste',
                'onmc' => '7175',
                'password' => '$2y$10$S1jtY3OfSGAJPN38B5GJp.tYFSS11AxQCyJnnG1myCf9cdCGPYf12',
                'remember_token' => 'DG1oqTpVNPY8IU8TCvimipuScI0Pl9gnwwm6imI9hWkoNRsygPPdyvWrYeQW',
                'created_at' => '2019-09-26 16:48:45',
                'updated_at' => '2019-09-26 16:48:45',
                'role_id' => '2',
            ),
            20 => 
            array (
                'id' => '21',
                'name' => 'KEMEZE',
                'prenom' => 'Sandrine',
                'login' => 'KEMEZE',
                'telephone' => '697112288',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Yaounde',
                'date_naissance' => '1984-11-30 16:48:45',
                'specialite' => 'Médecin généraliste',
                'onmc' => '8014',
                'password' => '$2y$10$tXbu6UihSHAJ4Owa4/4HnuIda1StXL9Xwsrwix6SI6/4nZN87MLSm',
                'remember_token' => NULL,
                'created_at' => '2019-09-26 16:48:45',
                'updated_at' => '2019-09-26 16:48:45',
                'role_id' => '2',
            ),
            21 => 
            array (
                'id' => '22',
                'name' => 'NGAYAP',
                'prenom' => 'FRANK',
                'login' => 'NGAYAP',
                'telephone' => '87203563',
                'sexe' => 'Masculin',
                'lieu_naissance' => 'Yaounde',
                'date_naissance' => '1984-11-30 16:48:45',
                'specialite' => 'Médecin généraliste',
                'onmc' => '0000',
                'password' => '$2y$10$QgH7JJwm66IQlQdla3NNX.6cZddHmKOpyEUokD0GXIX0bGXYPVL3G',
                'remember_token' => NULL,
                'created_at' => '2019-09-26 16:48:45',
                'updated_at' => '2019-09-26 16:48:45',
                'role_id' => '2',
            ),
            22 => 
            array (
                'id' => '23',
                'name' => 'TCHIEJI',
                'prenom' => 'Audrey',
                'login' => 'TCHIEJI',
                'telephone' => '18955451',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Yaounde',
                'date_naissance' => '1984-11-30 16:48:46',
                'specialite' => 'Médecin de travail',
                'onmc' => '0000',
                'password' => '$2y$10$hFNTQH.Suk/zECZ90BcDauRKLEupL5cVWyB.xrkwb4Lh0AkHUp426',
                'remember_token' => NULL,
                'created_at' => '2019-09-26 16:48:46',
                'updated_at' => '2019-09-26 16:48:46',
                'role_id' => '2',
            ),
            23 => 
            array (
                'id' => '24',
                'name' => 'HAPPI',
                'prenom' => 'Mireille',
                'login' => 'HAPPI',
                'telephone' => '80132593',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Yaounde',
                'date_naissance' => '1984-11-30 16:48:46',
                'specialite' => 'Pédiatre',
                'onmc' => '4609',
                'password' => '$2y$10$jNcxN6mcGnuGDY5FSv689.7C9Xia.d0EbgvKOYuUsZsSZrqsRHDGK',
                'remember_token' => NULL,
                'created_at' => '2019-09-26 16:48:46',
                'updated_at' => '2019-09-26 16:48:46',
                'role_id' => '2',
            ),
            24 => 
            array (
                'id' => '25',
                'name' => 'ENDALE TITI',
                'prenom' => 'AMELIE',
                'login' => 'TITI',
                'telephone' => '699838118',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1980-12-15 16:48:47',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$bO/KYdDZlLee0GJse/GKoe8br2uKdruTDy8SG3Pps8q2E75bDmmuG',
                'remember_token' => 'nptVPTQfOLxEa6sEXVwyaTfJQV44htry6WTZMkP7STcEgc0h4BhgTZgfv1y6',
                'created_at' => '2019-09-26 16:48:47',
                'updated_at' => '2019-09-26 16:48:47',
                'role_id' => '3',
            ),
            25 => 
            array (
                'id' => '26',
                'name' => 'ETINDELE',
                'prenom' => 'SANDRINE',
                'login' => 'ETINDELE',
                'telephone' => '1000',
                'sexe' => 'Féminin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1980-12-15 16:48:47',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$jVDQpXH/sypiDkQQA4lmBOJkur6MMW/n0GCSUaedASvhEsBWG1VIC',
                'remember_token' => 'X3HtU5hywbwBJwlrZUOrzMgYMSVzY2qtgiEdzPPmXA6Aj2UYXW363xhY7VpY',
                'created_at' => '2019-09-26 16:48:47',
                'updated_at' => '2019-09-26 16:48:47',
                'role_id' => '6',
            ),
            26 => 
            array (
                'id' => '27',
                'name' => 'NDOUMBE',
                'prenom' => 'CHRISTIAN',
                'login' => 'NDOUMBE',
                'telephone' => '20000',
                'sexe' => 'Masculin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1980-12-15 16:48:47',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$rSy4RPareeltcOMDSscwD.hnxkUZhZRkIoLKYsux62XN1pSeeFUzW',
                'remember_token' => 'JGA3DpoBFXQNUK66gXZ3n0kEVWRelyZOgErHTQDZptIGgerAg1CMJXMupoTY',
                'created_at' => '2019-09-26 16:48:47',
                'updated_at' => '2019-09-26 16:48:47',
                'role_id' => '9',
            ),
            27 => 
            array (
                'id' => '28',
                'name' => 'SANDJON',
                'prenom' => 'Jean Paul',
                'login' => 'Sjeanpaul',
                'telephone' => '1',
                'sexe' => 'Homme',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '2019-10-28',
                'specialite' => 'Chrirurgien urologue',
                'onmc' => '0000',
                'password' => '$2y$10$gpdemkxbpjt94wj9NNA.iuIBNS81j2eIPTAJNpBjmXxPvMX.cWere',
                'remember_token' => NULL,
                'created_at' => '2019-10-28 16:35:36',
                'updated_at' => '2019-10-28 16:35:36',
                'role_id' => '2',
            ),
            28 => 
            array (
                'id' => '29',
                'name' => 'EYOMGETA',
                'prenom' => 'Divine',
                'login' => 'DivineE',
                'telephone' => '2',
                'sexe' => 'Femme',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '2019-10-28',
                'specialite' => 'Chrirurgien urologue',
                'onmc' => '0000',
                'password' => '$2y$10$hUyKUrjrLTUYlRD0F9h2Zu/NFJaFUTdUsuAynTc.15F3SwQ9naAla',
                'remember_token' => NULL,
                'created_at' => '2019-10-28 16:37:07',
                'updated_at' => '2019-10-28 16:37:07',
                'role_id' => '2',
            ),
            29 => 
            array (
                'id' => '31',
                'name' => 'TOUKAM',
                'prenom' => 'Eve      .',
                'login' => 'ToukamE',
                'telephone' => '3',
                'sexe' => 'Femme',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '2019-10-28',
                'specialite' => 'Chrirurgien urologue',
                'onmc' => '0000',
                'password' => '$2y$10$D2o52DM2h2hCxAGSWj5aOeVKMukRwMxRZ0ljqvgHnzqClXoQUx2Oa',
                'remember_token' => NULL,
                'created_at' => '2019-10-28 16:42:48',
                'updated_at' => '2019-10-28 16:42:48',
                'role_id' => '2',
            ),
            30 => 
            array (
                'id' => '32',
                'name' => 'CHENDJOU',
                'prenom' => 'Brice   .',
                'login' => 'ChendjouB',
                'telephone' => '4',
                'sexe' => 'Homme',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '2019-10-28',
                'specialite' => 'Chrirurgien urologue',
                'onmc' => '0000',
                'password' => '$2y$10$BEMw43g9RSYetTxWISp3G.obRIWWb1SBmbheccQwnkTMVqJ9Cmxu.',
                'remember_token' => NULL,
                'created_at' => '2019-10-28 16:44:09',
                'updated_at' => '2019-10-28 16:44:09',
                'role_id' => '2',
            ),
            31 => 
            array (
                'id' => '33',
                'name' => 'EPOUPA NGALLE',
                'prenom' => 'Franck',
                'login' => 'EPFranck',
                'telephone' => '5',
                'sexe' => 'Homme',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '2019-10-28',
                'specialite' => 'Chrirurgien urologue',
                'onmc' => '0000',
                'password' => '$2y$10$GUaZLB6yLoG4eESwsqnszetoir3QBpjT1wCUshA3b2VbP/jMvUAUi',
                'remember_token' => NULL,
                'created_at' => '2019-10-28 16:45:09',
                'updated_at' => '2019-10-28 16:45:09',
                'role_id' => '2',
            ),
             32 => 
            array (
                'id' => '34',
                'name' => 'KOUAMO',
                'prenom' => 'STEPHANE',
                'login' => 'root',
                'telephone' => '2022',
                'sexe' => 'Masculin',
                'lieu_naissance' => 'Douala',
                'date_naissance' => '1980-12-15 16:48:47',
                'specialite' => NULL,
                'onmc' => NULL,
                'password' => '$2y$10$jVDQpXH/sypiDkQQA4lmBOJkur6MMW/n0GCSUaedASvhEsBWG1VIC',
                'remember_token' => 'X3HtU5hywbwBJwlrZUOrzMgYMSVzY2qtgiEdzPPmXA6Aj2UYXW363xhY7VpY',
                'created_at' => '2019-09-26 16:48:47',
                'updated_at' => '2019-09-26 16:48:47',
                'role_id' => '1',
            ),
          
        ));
        
        
    }
}